# ruff: noqa: RUF005, W505, E501
#   Style only, and suppressed rather than rewritten: this harness is
#   vendored from the campaign that produced the published numbers, and
#   e.g. adding zip(strict=True) would change behaviour where the
#   original silently truncated.  Correctness is gated by
#   validate_oracle.py, not by restyling proven code.
# Vendored verbatim from the soundness-campaign harness; see README.md.
# Experiment script, not library code: see artifacts/ndss27/README.md,
# "Lint and type checking", for why annotations are not required here.
# mypy: disable-error-code="no-untyped-def, no-untyped-call, type-arg, no-any-return, var-annotated, assignment, index, arg-type, union-attr, operator, attr-defined, misc, call-overload, return-value, unreachable"
"""Per-ISA instruction corpora for mt_multiarch.py / campaign_bits.py.

Each CORPORA[key](isa) -> list of (label, code_spec, src_regs[, constraints]):
  * keystone ISAs: code_spec = assembly string
  * riscv:         code_spec = hex machine code (no keystone for RISC-V)
  * src_regs   = registers the instruction READS and that may be tainted (GPRs
                 and/or flags); ALL GPRs+flags are checked as outputs regardless.
  * constraints = optional {reg: 'nonzero'}, pinning a register out of an
                 undefined domain for the WHOLE 2^k enumeration (a divisor must
                 be non-zero at every point of the cube, not just the base case,
                 or Unicorn traps mid-oracle).

Coverage goals, in rough order of how much they have caught:

  1. INSTRUCTION SHAPE.  Every real engine bug this session came from a shape not
     previously exercised (ARM64's shifted-register operand, MIPS `mul`'s
     truncate-then-sign-extend, RISC-V's computed shift mask).  So the corpora
     aim for shape variety -- widening, narrowing, extended-register operands,
     rotate-and-mask, multiply-accumulate, bit tests -- rather than long lists of
     near-identical mnemonics.
  2. FLAG PRODUCERS AND CONSUMERS.  adds/subs/cmp/tst produce; adc/sbc/cset/csel
     consume; ccmp both.
  3. OPERAND WIDTH.  32-bit forms on 64-bit ISAs, and x86's 32/16/8-bit
     sub-register writes, where a narrow write must preserve the upper bits'
     taint.
  4. MULTI-OUTPUT.  x86 `mul` writes RDX:RAX.

Known remaining gap: no LOAD/STORE anywhere, so the shadow-memory path and
address-taint handling are unexercised.  That needs memory support in the oracle
(seeding and reading a data page, plus threading memory taint into the worker),
which is a harness change rather than a corpus one.
"""


def _arm64(isa):
    F = ['NG', 'ZR', 'CY', 'OV']
    c = []

    def a(asm, srcs, cons=None):
        c.append((asm, asm, srcs, cons or {}))

    # --- arithmetic (+ flag production / consumption) ---
    a('add x0, x1, x2', ['x1', 'x2'])
    a('sub x0, x1, x2', ['x1', 'x2'])
    a('adds x0, x1, x2', ['x1', 'x2'])          # writes NZCV
    a('subs x0, x1, x2', ['x1', 'x2'])
    a('adc x0, x1, x2', ['x1', 'x2', 'CY'])     # reads carry
    a('sbc x0, x1, x2', ['x1', 'x2', 'CY'])
    a('adcs x0, x1, x2', ['x1', 'x2', 'CY'])    # reads carry, writes NZCV
    a('sbcs x0, x1, x2', ['x1', 'x2', 'CY'])
    a('neg x0, x1', ['x1'])
    a('negs x0, x1', ['x1'])
    a('ngc x0, x1', ['x1', 'CY'])
    a('ngcs x0, x1', ['x1', 'CY'])
    a('cmp x1, x2', ['x1', 'x2'])               # NZCV out, x0 unchanged
    a('cmn x1, x2', ['x1', 'x2'])
    a('add x0, x1, #1365', ['x1'])              # immediate forms
    a('sub x0, x1, #1365', ['x1'])
    a('adds x0, x1, #1365', ['x1'])
    a('cmp x1, #1365', ['x1'])
    a('cmn x1, #1365', ['x1'])
    # --- 32-bit (w) forms: the result zero-extends into the 64-bit register ---
    a('add w0, w1, w2', ['x1', 'x2'])
    a('sub w0, w1, w2', ['x1', 'x2'])
    a('adds w0, w1, w2', ['x1', 'x2'])
    a('and w0, w1, w2', ['x1', 'x2'])
    a('lsl w0, w1, w2', ['x1', 'x2'])
    a('asr w0, w1, #5', ['x1'])
    a('mul w0, w1, w2', ['x1', 'x2'])
    a('clz w0, w1', ['x1'])
    # --- shifted-register operands (barrel shifter feeding the ALU) ---
    a('add x0, x1, x2, lsl #3', ['x1', 'x2'])
    a('sub x0, x1, x2, asr #5', ['x1', 'x2'])
    a('add x0, x1, x2, lsr #7', ['x1', 'x2'])
    a('adds x0, x1, x2, lsl #2', ['x1', 'x2'])
    a('subs x0, x1, x2, asr #4', ['x1', 'x2'])
    a('and x0, x1, x2, lsl #6', ['x1', 'x2'])
    a('orr x0, x1, x2, lsr #9', ['x1', 'x2'])
    a('eor x0, x1, x2, ror #11', ['x1', 'x2'])
    a('bic x0, x1, x2, lsl #1', ['x1', 'x2'])
    a('cmp x1, x2, lsl #3', ['x1', 'x2'])
    # --- extended-register operands (zero/sign-extend then shift then ALU) ---
    a('add x0, x1, w2, uxtb', ['x1', 'x2'])
    a('add x0, x1, w2, uxth #2', ['x1', 'x2'])
    a('add x0, x1, w2, sxtb', ['x1', 'x2'])
    a('add x0, x1, w2, sxth #1', ['x1', 'x2'])
    a('sub x0, x1, w2, uxtw #3', ['x1', 'x2'])
    a('adds x0, x1, w2, sxtw', ['x1', 'x2'])
    # --- logic ---
    for m in ('and', 'orr', 'eor', 'bic', 'orn', 'eon'):
        a(f'{m} x0, x1, x2', ['x1', 'x2'])
    a('ands x0, x1, x2', ['x1', 'x2'])
    a('bics x0, x1, x2', ['x1', 'x2'])
    a('mvn x0, x1', ['x1'])
    a('tst x1, x2', ['x1', 'x2'])
    a('and x0, x1, #0xff00ff00ff00ff', ['x1'])   # logical-immediate encoding
    a('orr x0, x1, #0x5555555555555555', ['x1'])
    a('eor x0, x1, #0xffff0000ffff', ['x1'])
    # --- shifts / rotates ---
    for m in ('lsl', 'lsr', 'asr', 'ror'):
        a(f'{m} x0, x1, #7', ['x1'])
        a(f'{m} x0, x1, #1', ['x1'])
        a(f'{m} x0, x1, #63', ['x1'])
    for m in ('lslv', 'lsrv', 'asrv', 'rorv'):
        a(f'{m} x0, x1, x2', ['x1', 'x2'])
    a('extr x0, x1, x2, #13', ['x1', 'x2'])
    a('extr x0, x1, x2, #1', ['x1', 'x2'])
    # --- conditional set / select / compare (flag consumers) ---
    for cc in ('eq', 'ne', 'cs', 'cc', 'mi', 'pl', 'vs', 'vc', 'hi', 'ls', 'ge', 'lt', 'gt', 'le'):
        a(f'cset x0, {cc}', F)
    a('csetm x0, ge', F)
    for cc in ('eq', 'lt', 'hi', 'vs'):
        a(f'csel x0, x1, x2, {cc}', ['x1', 'x2'] + F)
        a(f'csinc x0, x1, x2, {cc}', ['x1', 'x2'] + F)
    a('csinv x0, x1, x2, mi', ['x1', 'x2'] + F)
    a('csneg x0, x1, x2, ne', ['x1', 'x2'] + F)
    a('cinc x0, x1, lt', ['x1'] + F)
    a('cinv x0, x1, ne', ['x1'] + F)
    a('cneg x0, x1, ge', ['x1'] + F)
    a('ccmp x1, x2, #5, eq', ['x1', 'x2'] + F)   # consumes AND produces NZCV
    a('ccmn x1, x2, #10, lt', ['x1', 'x2'] + F)
    a('ccmp x1, #7, #3, ne', ['x1'] + F)
    # --- extend / move ---
    for m in ('sxtb', 'sxth', 'sxtw', 'uxtb', 'uxth'):
        a(f'{m} x0, w1', ['x1'])
    a('mov x0, x1', ['x1'])
    a('movz x0, #0x1234, lsl #16', [])
    a('movn x0, #0x1234', [])
    a('movk x0, #0x1234, lsl #32', ['x0'])       # merges into the old value
    # --- bit manipulation ---
    for m in ('rbit', 'rev', 'rev16', 'rev32', 'clz', 'cls'):
        a(f'{m} x0, x1', ['x1'])
    a('ubfx x0, x1, #5, #17', ['x1'])
    a('sbfx x0, x1, #5, #17', ['x1'])
    a('ubfiz x0, x1, #9, #12', ['x1'])
    a('sbfiz x0, x1, #9, #12', ['x1'])
    a('bfi x0, x1, #8, #16', ['x0', 'x1'])       # insert: reads the old dest
    a('bfxil x0, x1, #4, #20', ['x0', 'x1'])
    # --- multiply / divide ---
    a('mul x0, x1, x2', ['x1', 'x2'])
    a('madd x0, x1, x2, x3', ['x1', 'x2', 'x3'])
    a('msub x0, x1, x2, x3', ['x1', 'x2', 'x3'])
    a('mneg x0, x1, x2', ['x1', 'x2'])
    a('smulh x0, x1, x2', ['x1', 'x2'])
    a('umulh x0, x1, x2', ['x1', 'x2'])
    a('smull x0, w1, w2', ['x1', 'x2'])
    a('umull x0, w1, w2', ['x1', 'x2'])
    a('smnegl x0, w1, w2', ['x1', 'x2'])
    a('umnegl x0, w1, w2', ['x1', 'x2'])
    a('smaddl x0, w1, w2, x3', ['x1', 'x2', 'x3'])
    a('umaddl x0, w1, w2, x3', ['x1', 'x2', 'x3'])
    a('smsubl x0, w1, w2, x3', ['x1', 'x2', 'x3'])
    a('sdiv x0, x1, x2', ['x1'], {'x2': 'nonzero'})
    a('udiv x0, x1, x2', ['x1'], {'x2': 'nonzero'})
    a('sdiv w0, w1, w2', ['x1'], {'x2': 'nonzero'})
    a('udiv w0, w1, w2', ['x1'], {'x2': 'nonzero'})
    # --- memory ROUND TRIPS (pinned stack pointer, untainted address) --------
    a('str x1, [sp, #-16]!; ldr x0, [sp], #16', ['x1'])
    a('stp x1, x2, [sp, #-16]!; ldp x0, x3, [sp], #16', ['x1', 'x2'])
    a('str x1, [sp, #-16]!; ldr w0, [sp], #16', ['x1'])
    a('strb w1, [sp, #-16]!; ldrb w0, [sp], #16', ['x1'])
    a('strh w1, [sp, #-16]!; ldrsh x0, [sp], #16', ['x1'])
    a('str x1, [sp, #-16]!; ldr x0, [sp]; add x0, x0, x2; add sp, sp, #16',
      ['x1', 'x2'])
    a('str x1, [sp, #-16]!; ldr x0, [sp]; eor x0, x0, x2; add sp, sp, #16',
      ['x1', 'x2'])
    # --- further integer coverage -------------------------------------------
    a('adds x0, x1, x2, lsr #3', ['x1', 'x2'])
    a('sbcs x0, x1, x2', ['x1', 'x2', 'CY'])
    a('orn x0, x1, x2, lsl #4', ['x1', 'x2'])
    a('eon x0, x1, x2, lsr #6', ['x1', 'x2'])
    a('bics x0, x1, x2, asr #2', ['x1', 'x2'])
    a('and x0, x1, x2, asr #7', ['x1', 'x2'])
    a('rev64 x0, x1', ['x1'])
    a('extr x0, x1, x2, #63', ['x1', 'x2'])
    a('ubfx x0, x1, #0, #1', ['x1'])
    a('sbfx x0, x1, #63, #1', ['x1'])
    a('lslv w0, w1, w2', ['x1', 'x2'])
    a('asrv w0, w1, w2', ['x1', 'x2'])
    a('madd w0, w1, w2, w3', ['x1', 'x2', 'x3'])
    a('smulh x0, x1, x1', ['x1'])
    a('ccmp x1, x2, #0, al', ['x1', 'x2'] + F)
    # --- further shapes (shifted-operand logic variants, bitfield clear) ---
    a('and x0, x1, x2, ror #5', ['x1', 'x2'])
    a('orr x0, x1, x2, asr #3', ['x1', 'x2'])
    a('sub x0, x1, x2, lsr #4', ['x1', 'x2'])
    a('eor x0, x1, x2, asr #7', ['x1', 'x2'])
    a('madd x0, x1, x2, xzr', ['x1', 'x2'])
    a('bfc x0, #4, #8', ['x0'])
    # --- July 23 campaign: verified-sound enumerated instructions ---
    a('add x0, x1, x2, asr #5', ['x2', 'x1'])
    a('add x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('adds x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('adds x0, x1, x2, asr #5', ['x2', 'x1'])
    a('adds x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('sub x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('subs w0, w1, w2', ['x2', 'x1'])
    a('subs x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('subs x0, x1, x2, asr #5', ['x2', 'x1'])
    a('subs x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('adc w0, w1, w2', ['CY', 'x1', 'x2'])
    a('adcs w0, w1, w2', ['CY', 'x1', 'x2'])
    a('sbc w0, w1, w2', ['CY', 'x2', 'x1'])
    a('sbcs w0, w1, w2', ['CY', 'x2', 'x1'])
    a('neg w0, w1', ['x1'])
    a('neg x1, x2', ['x2'])
    a('neg x1, x2, lsl #3', ['x2'])
    a('negs w0, w1', ['x1'])
    a('negs x1, x2', ['x2'])
    a('negs x1, x2, lsl #3', ['x2'])
    a('ngc w0, w1', ['CY', 'x1'])
    a('ngc x1, x2', ['CY', 'x2'])
    a('ngcs w0, w1', ['CY', 'x1'])
    a('ngcs x1, x2', ['CY', 'x2'])
    a('and x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('and x0, x1, x2, asr #5', ['x2', 'x1'])
    a('and x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('ands w0, w1, w2', ['x1', 'x2'])
    a('ands x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('ands x0, x1, x2, asr #5', ['x2', 'x1'])
    a('ands x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('orr w0, w1, w2', ['x1', 'x2'])
    a('orr x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('orr x0, x1, x2, asr #5', ['x2', 'x1'])
    a('orr x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('eor w0, w1, w2', ['x1', 'x2'])
    a('eor x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('eor x0, x1, x2, asr #5', ['x2', 'x1'])
    a('eor x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('bic w0, w1, w2', ['x2', 'x1'])
    a('bic x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('bic x0, x1, x2, asr #5', ['x2', 'x1'])
    a('bic x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('bics w0, w1, w2', ['x2', 'x1'])
    a('bics x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('bics x0, x1, x2, asr #5', ['x2', 'x1'])
    a('bics x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('orn w0, w1, w2', ['x2', 'x1'])
    a('orn x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('orn x0, x1, x2, asr #5', ['x2', 'x1'])
    a('orn x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('eon w0, w1, w2', ['x2', 'x1'])
    a('eon x0, x1, x2, lsl #3', ['x2', 'x1'])
    a('eon x0, x1, x2, asr #5', ['x2', 'x1'])
    a('eon x0, x1, x2, lsr #4', ['x2', 'x1'])
    a('mvn w0, w1', ['x1'])
    a('mvn x1, x2', ['x2'])
    a('mvn x1, x2, lsl #3', ['x2'])
    a('tst x0, x1', ['x0', 'x1'])
    a('tst w0, w1', ['x0', 'x1'])
    a('tst x1, x2, lsl #3', ['x2', 'x1'])
    a('mneg w0, w1, w2', ['x1', 'x2'])
    a('umsubl x0, w1, w2, x3', ['x1', 'x2', 'x3'])
    a('lsl x0, x1, #5', ['x1'])
    a('lsl w0, w1, #3', ['x1'])
    a('lsr w0, w1, w2', ['x2', 'x1'])
    a('lsr x0, x1, #5', ['x1'])
    a('lsr w0, w1, #3', ['x1'])
    a('asr x0, x1, #5', ['x1'])
    a('asr w0, w1, #3', ['x1'])
    a('ror w0, w1, w2', ['x2', 'x1'])
    a('ror x0, x1, #5', ['x1'])
    a('ror w0, w1, #3', ['x1'])
    a('cmp x0, x1', ['x1', 'x0'])
    a('cmp w0, w1', ['x1', 'x0'])
    a('cmn x0, x1', ['x1', 'x0'])
    a('cmn w0, w1', ['x1', 'x0'])
    a('cmn x1, x2, lsl #3', ['x2', 'x1'])
    a('ccmn x1, x2, #0, al', ['x2', 'x1'])
    a('csinv x0, x1, x2, eq', ['x1', 'ZR', 'x2'])
    a('csneg x0, x1, x2, eq', ['x1', 'ZR', 'x2'])
    a('csetm x0, eq', ['ZR'])
    a('cinc x0, x1, eq', ['x1', 'ZR'])
    a('cinv x0, x1, eq', ['x1', 'ZR'])
    a('cneg x0, x1, eq', ['x1', 'ZR'])
    a('clz x1, x2', ['x2'])
    a('cls w0, w1', ['x1'])
    a('cls x1, x2', ['x2'])
    a('rbit w0, w1', ['x1'])
    a('rbit x1, x2', ['x2'])
    a('rev w0, w1', ['x1'])
    a('rev x1, x2', ['x2'])
    a('rev16 w0, w1', ['x1'])
    a('rev16 x1, x2', ['x2'])
    a('rev32 x1, x2', ['x2'])
    a('sxtb w0, w1', ['x1'])
    a('sxtb x1, x2', ['x2'])
    a('sxth w0, w1', ['x1'])
    a('sxth x1, x2', ['x2'])
    a('sxtw x1, x2', ['x2'])
    a('bfm x0, x1, #4, #10', ['x1', 'x0'])
    a('sbfm x0, x1, #4, #10', ['x1'])
    a('ubfm x0, x1, #4, #10', ['x1'])
    a('bfi x0, x1, #4, #10', ['x0', 'x1'])
    a('bfxil x0, x1, #4, #10', ['x1', 'x0'])
    a('sbfx x0, x1, #4, #10', ['x1'])
    a('ubfx x0, x1, #4, #10', ['x1'])
    a('sbfiz x0, x1, #4, #10', ['x1'])
    a('ubfiz x0, x1, #4, #10', ['x1'])
    a('movk x0, #0x1234', ['x0'])
    a('movk x0, #0x1234, lsl #16', ['x0'])
    a('crc32b w0, w1, w2', ['x1', 'x2'])
    a('crc32h w0, w1, w2', ['x1', 'x2'])
    a('crc32w w0, w1, w2', ['x1', 'x2'])
    a('crc32cb w0, w1, w2', ['x1', 'x2'])
    a('crc32ch w0, w1, w2', ['x1', 'x2'])
    a('crc32cw w0, w1, w2', ['x1', 'x2'])
    # --- July 23 campaign (batch 2): capped register variants + memory-operand shapes ---
    a('add x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('add x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('add x0, x1, x2, asr #1', ['x2', 'x1'])
    a('add x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('add x0, x1, w2, uxtb #2', ['x2', 'x1'])
    a('add x0, x1, #0', ['x1'])
    a('adds x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('adds x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('adds x0, x1, x2, asr #1', ['x2', 'x1'])
    a('adds x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('adds x0, x1, w2, uxtb #2', ['x2', 'x1'])
    a('adds x0, x1, #0', ['x1'])
    a('sub x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('sub x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('sub x0, x1, x2, asr #1', ['x2', 'x1'])
    a('sub x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('sub x0, x1, #0', ['x1'])
    a('subs x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('subs x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('subs x0, x1, x2, asr #1', ['x2', 'x1'])
    a('subs x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('subs x0, x1, #0', ['x1'])
    a('and x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('and x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('and x0, x1, x2, asr #1', ['x2', 'x1'])
    a('and x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('and x0, x1, #4095', ['x1'])
    a('ands x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('ands x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('ands x0, x1, x2, asr #1', ['x2', 'x1'])
    a('ands x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('ands x0, x1, #4095', ['x1'])
    a('orr x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('orr x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('orr x0, x1, x2, asr #1', ['x2', 'x1'])
    a('orr x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('orr x0, x1, #4095', ['x1'])
    a('eor x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('eor x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('eor x0, x1, x2, asr #1', ['x2', 'x1'])
    a('eor x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('eor x0, x1, #4095', ['x1'])
    a('bic x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('bic x0, x1, x2, asr #1', ['x2', 'x1'])
    a('bic x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('bic x0, x1, #4095', ['x1'])
    a('bics x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('bics x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('bics x0, x1, x2, asr #1', ['x2', 'x1'])
    a('bics x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('bics x0, x1, #4095', ['x1'])
    a('orn x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('orn x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('orn x0, x1, x2, asr #1', ['x2', 'x1'])
    a('orn x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('orn x0, x1, #4095', ['x1'])
    a('eon x0, x1, x2, lsl #1', ['x2', 'x1'])
    a('eon x0, x1, x2, lsl #7', ['x2', 'x1'])
    a('eon x0, x1, x2, asr #1', ['x2', 'x1'])
    a('eon x0, x1, x2, lsr #32', ['x2', 'x1'])
    a('eon x0, x1, #4095', ['x1'])
    a('lsl x0, x1, #0', ['x1'])
    a('asr x0, x1, #0', ['x1'])
    a('ror x0, x1, #0', ['x1'], {'exclude_flags': ['OF']})
    a('ccmp x0, x1, #0, ne', ['ZR', 'x1', 'x0'])
    a('ccmn x0, x1, #0, ne', ['ZR', 'x1', 'x0'])
    a('csel x0, x1, x2, ne', ['ZR', 'x1', 'x2'])
    a('csel x0, x1, x2, cs', ['x1', 'CY', 'x2'])
    a('csel x0, x1, x2, mi', ['x1', 'NG', 'x2'])
    a('csel x0, x1, x2, ge', ['NG', 'OV', 'x1', 'x2'])
    a('csel x0, x1, x2, gt', ['ZR', 'NG', 'OV', 'x1', 'x2'])
    a('csinc x0, x1, x2, ne', ['ZR', 'x1', 'x2'])
    a('csinc x0, x1, x2, cs', ['x1', 'CY', 'x2'])
    a('csinc x0, x1, x2, mi', ['x1', 'NG', 'x2'])
    a('csinc x0, x1, x2, ge', ['NG', 'OV', 'x1', 'x2'])
    a('csinc x0, x1, x2, gt', ['ZR', 'NG', 'OV', 'x1', 'x2'])
    a('csinv x0, x1, x2, ne', ['ZR', 'x1', 'x2'])
    a('csinv x0, x1, x2, cs', ['x1', 'CY', 'x2'])
    a('csinv x0, x1, x2, ge', ['NG', 'OV', 'x1', 'x2'])
    a('csinv x0, x1, x2, lt', ['NG', 'OV', 'x1', 'x2'])
    a('csinv x0, x1, x2, gt', ['ZR', 'NG', 'OV', 'x1', 'x2'])
    a('csneg x0, x1, x2, cs', ['x1', 'CY', 'x2'])
    a('csneg x0, x1, x2, mi', ['x1', 'NG', 'x2'])
    a('csneg x0, x1, x2, ge', ['NG', 'OV', 'x1', 'x2'])
    a('csneg x0, x1, x2, lt', ['NG', 'OV', 'x1', 'x2'])
    a('csneg x0, x1, x2, gt', ['ZR', 'NG', 'OV', 'x1', 'x2'])
    a('cinc x0, x1, ne', ['ZR', 'x1'])
    a('cneg x0, x1, ne', ['ZR', 'x1'])
    a('bfm x0, x1, #0, #16', ['x1', 'x0'])
    a('bfm x0, x1, #8, #8', ['x1', 'x0'])
    a('bfm x0, x1, #16, #16', ['x1', 'x0'])
    a('sbfm x0, x1, #0, #16', ['x1'])
    a('sbfm x0, x1, #8, #8', ['x1'])
    a('sbfm x0, x1, #16, #16', ['x1'])
    a('ubfm x0, x1, #0, #16', ['x1'])
    a('ubfm x0, x1, #8, #8', ['x1'])
    a('ubfm x0, x1, #16, #16', ['x1'])
    a('bfi x0, x1, #0, #16', ['x1', 'x0'])
    a('bfi x0, x1, #8, #8', ['x0', 'x1'])
    a('bfi x0, x1, #16, #16', ['x0', 'x1'])
    a('bfxil x0, x1, #8, #8', ['x1', 'x0'])
    a('bfxil x0, x1, #16, #16', ['x1', 'x0'])
    a('sbfx x0, x1, #8, #8', ['x1'])
    a('sbfx x0, x1, #16, #16', ['x1'])
    a('ubfx x0, x1, #0, #16', ['x1'])
    a('ubfx x0, x1, #8, #8', ['x1'])
    a('ubfx x0, x1, #16, #16', ['x1'])
    a('sbfiz x0, x1, #8, #8', ['x1'])
    a('sbfiz x0, x1, #16, #16', ['x1'])
    a('ubfiz x0, x1, #8, #8', ['x1'])
    a('ubfiz x0, x1, #16, #16', ['x1'])
    a('str x1, [sp, #-16]; ldr x0, [sp, #-16]', ['x1'])
    a('str w1, [sp, #-16]; ldr w0, [sp, #-16]', ['x1'])
    a('strb w1, [sp, #-16]; ldrb w0, [sp, #-16]', ['x1'])
    a('strh w1, [sp, #-16]; ldrh w0, [sp, #-16]', ['x1'])
    return c


def _mips(isa):
    c = []

    def a(asm, srcs, cons=None):
        c.append((asm, asm, srcs, cons or {}))

    # --- 32-bit register-register ---
    for m in ('addu', 'subu', 'and', 'or', 'xor', 'nor', 'slt', 'sltu', 'movz', 'movn',
              'sllv', 'srlv', 'srav'):
        a(f'{m} $2, $4, $5', ['A0', 'A1'])
    a('add $2, $4, $5', ['A0', 'A1'])
    a('sub $2, $4, $5', ['A0', 'A1'])
    # --- 32-bit shifts by immediate ---
    for m in ('sll', 'srl', 'sra'):
        for sh in (1, 7, 31):
            a(f'{m} $2, $4, {sh}', ['A0'])
    # --- immediates ---
    a('addiu $2, $4, 1365', ['A0'])
    a('addiu $2, $4, -1365', ['A0'])
    a('andi $2, $4, 0xff0f', ['A0'])
    a('ori $2, $4, 0x0ff0', ['A0'])
    a('xori $2, $4, 0xf00f', ['A0'])
    a('slti $2, $4, 1365', ['A0'])
    a('sltiu $2, $4, 1365', ['A0'])
    a('lui $2, 0x1234', [])
    # --- 64-bit forms ---
    for m in ('daddu', 'dsubu'):
        a(f'{m} $2, $4, $5', ['A0', 'A1'])
    # dsllv/dsrlv/dsrav are EXCLUDED: Ghidra's MIPS64 SLEIGH lifts them as a bare
    # `v0 = a0 << a1` with no shift-amount masking, while the hardware masks to 6
    # bits.  Verified: a0=1, a1=100 gives 1<<36 on Unicorn and 0 under p-code
    # (a shift >= width saturates).  The oracle therefore cannot ground-truth them
    # against an engine that faithfully implements the model -- the same class as
    # x86's `shl` OF, which SLEIGH preserves where the hardware computes it.
    for m in ('dsll', 'dsrl', 'dsra'):
        a(f'{m} $2, $4, 7', ['A0'])
    a('dsll32 $2, $4, 7', ['A0'])
    a('dsra32 $2, $4, 7', ['A0'])
    # --- multiply / divide ---
    a('mul $2, $4, $5', ['A0', 'A1'])
    a('div $zero, $4, $5', ['A0'], {'A1': 'nonzero'})
    a('divu $zero, $4, $5', ['A0'], {'A1': 'nonzero'})
    # --- bit manipulation / counting ---
    a('clz $2, $4', ['A0'])
    a('clo $2, $4', ['A0'])
    # NOTE: MIPS32r2 forms (rotr/rotrv/seb/seh/wsbh/ext/ins) are omitted because
    # keystone's MIPS64 mode does not enable that CPU feature.
    a('dclz $2, $4', ['A0'])
    # --- memory ROUND TRIPS (pinned stack pointer, untainted address) --------
    a('sw $4, -16($sp); lw $2, -16($sp)', ['A0'])
    a('sw $4, -16($sp); lw $2, -16($sp); addu $2, $2, $5', ['A0', 'A1'])
    a('sw $4, -16($sp); lw $2, -16($sp); xor $2, $2, $5', ['A0', 'A1'])
    a('sb $4, -16($sp); lb $2, -16($sp)', ['A0'])
    a('sh $4, -16($sp); lhu $2, -16($sp)', ['A0'])
    a('sd $4, -16($sp); ld $2, -16($sp)', ['A0'])
    # --- further integer coverage -------------------------------------------
    a('and $2, $4, $4', ['A0'])
    a('subu $2, $zero, $4', ['A0'])
    a('sltu $2, $zero, $4', ['A0'])
    a('srlv $2, $4, $4', ['A0'])
    a('dsrl32 $2, $4, 7', ['A0'])
    a('mul $2, $4, $4', ['A0'])
    # --- July 23 campaign: verified-sound enumerated instructions ---
    a('add $2, $4, 7', ['A0'])
    a('add $2, $4, 100', ['A0'])
    a('add $2, $4', ['V0', 'A0'])
    a('add $4, $5', ['A0', 'A1'])
    a('addu $2, $4, 7', ['A0'])
    a('addu $2, $4, 100', ['A0'])
    a('addu $2, $4', ['V0', 'A0'])
    a('addu $4, $5', ['A0', 'A1'])
    a('addi $2, 0x1234', ['V0'])
    a('addiu $2, 0x1234', ['V0'])
    a('sub $2, $4, 7', ['A0'])
    a('sub $2, $4, 100', ['A0'])
    a('sub $2, $4', ['V0', 'A0'])
    a('sub $4, $5', ['A0', 'A1'])
    a('subu $2, $4, 7', ['A0'])
    a('subu $2, $4, 100', ['A0'])
    a('subu $2, $4', ['V0', 'A0'])
    a('subu $4, $5', ['A0', 'A1'])
    a('and $2, $4, 7', ['A0'])
    a('and $2, $4, 100', ['A0'])
    a('and $2, $4', ['V0', 'A0'])
    a('and $4, $5', ['A0', 'A1'])
    a('andi $2, 0x1234', ['V0'])
    a('or $2, $4, 7', ['A0'])
    a('or $2, $4, 100', ['A0'])
    a('or $2, $4', ['V0', 'A0'])
    a('or $4, $5', ['A0', 'A1'])
    a('ori $2, 0x1234', ['V0'])
    a('xor $2, $4, 7', ['A0'])
    a('xor $2, $4, 100', ['A0'])
    a('xor $2, $4', ['V0', 'A0'])
    a('xor $4, $5', ['A0', 'A1'])
    a('xori $2, 0x1234', ['V0'])
    a('nor $2, $4, 7', ['A0'])
    a('nor $2, $4, 100', ['A0'])
    a('slt $2, $4, 7', ['A0'])
    a('slt $2, $4, 100', ['A0'])
    a('sltu $2, $4, 7', ['A0'])
    a('sltu $2, $4, 100', ['A0'])
    a('mul $2, $4', ['V0', 'A0'])
    a('mul $4, $5', ['A0', 'A1'])
    a('clo $4, $5', ['A1'])
    a('clz $4, $5', ['A1'])
    a('dclo $2, $4', ['A0'])
    a('dclo $4, $5', ['A1'])
    a('dclz $4, $5', ['A1'])
    a('dadd $2, $4, $5', ['A0', 'A1'])
    a('dadd $2, $4, 7', ['A0'])
    a('dadd $2, $4, 100', ['A0'])
    a('dadd $2, $4', ['V0', 'A0'])
    a('dadd $4, $5', ['A0', 'A1'])
    a('daddu $2, $4, 7', ['A0'])
    a('daddu $2, $4, 100', ['A0'])
    a('daddu $2, $4', ['V0', 'A0'])
    a('daddu $4, $5', ['A0', 'A1'])
    a('dsub $2, $4, $5', ['A0', 'A1'])
    a('dsub $2, $4, 7', ['A0'])
    a('dsub $2, $4, 100', ['A0'])
    a('dsub $2, $4', ['V0', 'A0'])
    a('dsub $4, $5', ['A0', 'A1'])
    a('dsubu $2, $4, 7', ['A0'])
    a('dsubu $2, $4, 100', ['A0'])
    a('dsubu $2, $4', ['V0', 'A0'])
    a('dsubu $4, $5', ['A0', 'A1'])
    a('daddiu $2, 0x1234', ['V0'])
    a('negu $4, $5', ['A1'])
    # --- July 23 campaign (batch 2): capped register variants + memory-operand shapes ---
    a('add $2, $4, 0', ['A0'])
    a('add $2, $4, 1', ['A0'])
    a('add $2, $4, 15', ['A0'])
    a('add $2, $4, 31', ['A0'])
    a('add $2, $4, 0x7fff', ['A0'])
    a('add $2, $4, -1', ['A0'])
    a('addu $2, $4, 0', ['A0'])
    a('addu $2, $4, 1', ['A0'])
    a('addu $2, $4, 15', ['A0'])
    a('addu $2, $4, 31', ['A0'])
    a('addu $2, $4, 0x7fff', ['A0'])
    a('addu $2, $4, -1', ['A0'])
    a('sub $2, $4, 15', ['A0'])
    a('sub $2, $4, 31', ['A0'])
    a('sub $2, $4, 0x7fff', ['A0'])
    a('subu $2, $4, 15', ['A0'])
    a('subu $2, $4, 31', ['A0'])
    a('subu $2, $4, 0x7fff', ['A0'])
    a('and $2, $4, 0', ['A0'])
    a('and $2, $4, 1', ['A0'])
    a('and $2, $4, 15', ['A0'])
    a('and $2, $4, 31', ['A0'])
    a('and $2, $4, 0x7fff', ['A0'])
    a('and $2, $4, -1', ['A0'])
    a('or $2, $4, 0', ['A0'])
    a('or $2, $4, 1', ['A0'])
    a('or $2, $4, 15', ['A0'])
    a('or $2, $4, 31', ['A0'])
    a('or $2, $4, 0x7fff', ['A0'])
    a('or $2, $4, -1', ['A0'])
    a('xor $2, $4, 0', ['A0'])
    a('xor $2, $4, 1', ['A0'])
    a('xor $2, $4, 15', ['A0'])
    a('xor $2, $4, 31', ['A0'])
    a('xor $2, $4, 0x7fff', ['A0'])
    a('xor $2, $4, -1', ['A0'])
    a('nor $2, $4, 0', ['A0'])
    a('nor $2, $4, 1', ['A0'])
    a('nor $2, $4, 15', ['A0'])
    a('nor $2, $4, 31', ['A0'])
    a('nor $2, $4, 0x7fff', ['A0'])
    a('nor $2, $4, -1', ['A0'])
    a('slt $2, $4, 0', ['A0'])
    a('slt $2, $4, 1', ['A0'])
    a('slt $2, $4, 15', ['A0'])
    a('slt $2, $4, 31', ['A0'])
    a('slt $2, $4, 0x7fff', ['A0'])
    a('slt $2, $4, -1', ['A0'])
    a('sltu $2, $4, 0', ['A0'])
    a('sltu $2, $4, 1', ['A0'])
    a('sltu $2, $4, 15', ['A0'])
    a('sltu $2, $4, 31', ['A0'])
    a('sltu $2, $4, 0x7fff', ['A0'])
    a('sltu $2, $4, -1', ['A0'])
    a('sll $2, $4, 0', ['A0'])
    a('sll $2, $4, 15', ['A0'])
    a('srl $2, $4, 0', ['A0'])
    a('srl $2, $4, 15', ['A0'])
    a('sra $2, $4, 0', ['A0'])
    a('sra $2, $4, 15', ['A0'])
    a('dsll32 $2, $4, 0', ['A0'])
    a('dsll32 $2, $4, 1', ['A0'])
    a('dsll32 $2, $4, 15', ['A0'])
    a('dsll32 $2, $4, 31', ['A0'])
    a('dsrl32 $2, $4, 0', ['A0'])
    a('dsrl32 $2, $4, 1', ['A0'])
    a('dsrl32 $2, $4, 15', ['A0'])
    a('dsrl32 $2, $4, 31', ['A0'])
    a('dsra32 $2, $4, 0', ['A0'])
    a('dsra32 $2, $4, 1', ['A0'])
    a('dsra32 $2, $4, 15', ['A0'])
    a('dsra32 $2, $4, 31', ['A0'])
    a('dadd $2, $4, 0', ['A0'])
    a('dadd $2, $4, 1', ['A0'])
    a('dadd $2, $4, 15', ['A0'])
    a('dadd $2, $4, 31', ['A0'])
    a('dadd $2, $4, 0x7fff', ['A0'])
    a('dadd $2, $4, -1', ['A0'])
    a('daddu $2, $4, 0', ['A0'])
    a('daddu $2, $4, 1', ['A0'])
    a('daddu $2, $4, 15', ['A0'])
    a('daddu $2, $4, 31', ['A0'])
    a('daddu $2, $4, 0x7fff', ['A0'])
    a('daddu $2, $4, -1', ['A0'])
    a('dsub $2, $4, 15', ['A0'])
    a('dsub $2, $4, 31', ['A0'])
    a('dsub $2, $4, 0x7fff', ['A0'])
    a('dsubu $2, $4, 15', ['A0'])
    a('dsubu $2, $4, 31', ['A0'])
    a('dsubu $2, $4, 0x7fff', ['A0'])
    a('sw $4, 0($sp); lw $2, 0($sp)', ['A0'])
    a('sb $4, 0($sp); lb $2, 0($sp)', ['A0'])
    a('sb $4, 0($sp); lbu $2, 0($sp)', ['A0'])
    a('sh $4, 0($sp); lh $2, 0($sp)', ['A0'])
    a('sh $4, 0($sp); lhu $2, 0($sp)', ['A0'])
    a('sd $4, 0($sp); ld $2, 0($sp)', ['A0'])
    return c


def _ppc(isa):
    c = []

    def a(asm, srcs, cons=None):
        c.append((asm, asm, srcs, cons or {}))

    # --- register-register arithmetic / logic ---
    for m in ('add', 'subf', 'and', 'or', 'xor', 'nand', 'nor', 'eqv', 'andc', 'orc'):
        a(f'{m} 3, 4, 5', ['R4', 'R5'])
    for m in ('slw', 'srw', 'sraw', 'mullw', 'mulhw', 'mulhwu'):
        a(f'{m} 3, 4, 5', ['R4', 'R5'])
    a('neg 3, 4', ['R4'])
    a('extsb 3, 4', ['R4'])
    a('extsh 3, 4', ['R4'])
    a('cntlzw 3, 4', ['R4'])
    # --- shifts / rotate-and-mask: the canonical PPC bitfield ops ---
    a('slwi 3, 4, 7', ['R4'])
    a('srwi 3, 4, 7', ['R4'])
    a('srawi 3, 4, 7', ['R4'])
    a('srawi 3, 4, 31', ['R4'])
    a('rlwinm 3, 4, 5, 8, 20', ['R4'])
    a('rlwinm 3, 4, 0, 16, 31', ['R4'])
    a('rlwinm 3, 4, 12, 0, 19', ['R4'])
    a('rlwnm 3, 4, 5, 8, 20', ['R4', 'R5'])
    a('rlwimi 3, 4, 5, 8, 20', ['R3', 'R4'])     # inserts into the old dest
    a('rotlwi 3, 4, 9', ['R4'])
    # --- immediates ---
    a('addi 3, 4, 1365', ['R4'])
    a('addis 3, 4, 1365', ['R4'])
    a('subfic 3, 4, 1365', ['R4'])
    a('andi. 3, 4, 0xff0f', ['R4'])              # -> cr0
    a('ori 3, 4, 0x0ff0', ['R4'])
    a('xori 3, 4, 0xf00f', ['R4'])
    a('mulli 3, 4, 1365', ['R4'])
    # --- flag producers / consumers ---
    a('addc 3, 4, 5', ['R4', 'R5'])              # -> xer_ca
    # adde/subfe/addze READ xer_ca -- excluded: Unicorn's PPC models no XER carry, so
    # neither the oracle nor a consistent state format can represent their carry-in.
    a('subfc 3, 4, 5', ['R4', 'R5'])
    a('cmpw 0, 4, 5', ['R4', 'R5'])              # -> cr0
    a('cmplw 0, 4, 5', ['R4', 'R5'])
    a('cmpwi 0, 4, 1365', ['R4'])
    a('cmplwi 0, 4, 1365', ['R4'])
    a('and. 3, 4, 5', ['R4', 'R5'])              # -> cr0
    a('or. 3, 4, 5', ['R4', 'R5'])
    a('add. 3, 4, 5', ['R4', 'R5'])
    a('subf. 3, 4, 5', ['R4', 'R5'])
    a('neg. 3, 4', ['R4'])
    a('srawi. 3, 4, 7', ['R4'])
    # --- divide ---
    a('divw 3, 4, 5', ['R4'], {'R5': 'nonzero'})
    a('divwu 3, 4, 5', ['R4'], {'R5': 'nonzero'})
    # --- memory ROUND TRIPS (pinned stack pointer, untainted address) --------
    a('stw 4, -16(1); lwz 3, -16(1)', ['R4'])
    a('stw 4, -16(1); lwz 3, -16(1); add 3, 3, 5', ['R4', 'R5'])
    a('stw 4, -16(1); lwz 3, -16(1); xor 3, 3, 5', ['R4', 'R5'])
    a('stb 4, -16(1); lbz 3, -16(1)', ['R4'])
    a('sth 4, -16(1); lha 3, -16(1)', ['R4'])
    # --- further integer coverage -------------------------------------------
    a('rlwinm 3, 4, 31, 0, 31', ['R4'])
    a('rlwinm. 3, 4, 5, 8, 20', ['R4'])
    a('srawi 3, 4, 1', ['R4'])
    a('nor 3, 4, 4', ['R4'])
    a('andc 3, 4, 5', ['R4', 'R5'])
    a('mulhw 3, 4, 4', ['R4'])
    a('cmpw 1, 4, 5', ['R4', 'R5'])
    # --- shifted-immediate logicals and unsigned high multiply ---
    a('andis. 3, 4, 0x1234', ['R4'])
    a('oris 3, 4, 0x1234', ['R4'])
    a('xoris 3, 4, 0x1234', ['R4'])
    a('mulhwu 3, 4, 5', ['R4', 'R5'])
    # --- July 23 campaign: verified-sound enumerated instructions ---
    a('add 3, 4, 7', ['R4'])
    a('add 0, 3, 4', ['R3', 'R4'])
    a('addc 3, 4, 7', ['R4'])
    a('addc 0, 3, 4', ['R3', 'R4'])
    a('subf 3, 4, 7', ['R4'])
    a('subf 0, 3, 4', ['R4', 'R3'])
    a('subfc 3, 4, 7', ['R4'])
    a('subfc 0, 3, 4', ['R3', 'R4'])
    a('subfic 3, 4, 5', ['R4'])
    a('subfic 3, 4, 7', ['R4'])
    a('subfic 3, 4, 0x1234', ['R4'])
    a('subfic 0, 3, 4', ['R3'])
    a('addi 3, 4, 5', ['R4'])
    a('addi 3, 4, 7', ['R4'])
    a('addi 3, 4, 0x1234', ['R4'])
    a('addi 0, 3, 4', ['R3'])
    a('addis 3, 4, 5', ['R4'])
    a('addis 3, 4, 7', ['R4'])
    a('addis 3, 4, 0x1234', ['R4'])
    a('addis 0, 3, 4', ['R3'])
    a('addic 3, 4, 5', ['R4'])
    a('addic 3, 4, 7', ['R4'])
    a('addic 3, 4, 0x1234', ['R4'])
    a('addic 0, 3, 4', ['R3'])
    a('and 3, 4, 7', ['R4'])
    a('and 0, 3, 4', ['R3', 'R4'])
    a('andc 3, 4, 7', ['R4'])
    a('andc 0, 3, 4', ['R4', 'R3'])
    a('or 3, 4, 7', ['R4'])
    a('or 0, 3, 4', ['R3', 'R4'])
    a('orc 3, 4, 7', ['R4'])
    a('orc 0, 3, 4', ['R4', 'R3'])
    a('xor 3, 4, 7', ['R4'])
    a('xor 0, 3, 4', ['R3', 'R4'])
    a('nand 3, 4, 7', ['R4'])
    a('nand 0, 3, 4', ['R3', 'R4'])
    a('nor 3, 4, 7', ['R4'])
    a('nor 0, 3, 4', ['R3', 'R4'])
    a('eqv 3, 4, 7', ['R4'])
    a('eqv 0, 3, 4', ['R3', 'R4'])
    a('andi. 3, 4, 5', ['R4', 'cr0'])
    a('andi. 3, 4, 7', ['R4', 'cr0'])
    a('andi. 3, 4, 0x1234', ['R4', 'cr0'])
    a('andi. 0, 3, 4', ['R3', 'cr0'])
    a('andis. 3, 4, 5', ['R4', 'cr0'])
    a('andis. 3, 4, 7', ['R4', 'cr0'])
    a('andis. 0, 3, 4', ['R3', 'cr0'])
    a('ori 3, 4, 5', ['R4'])
    a('ori 3, 4, 7', ['R4'])
    a('ori 3, 4, 0x1234', ['R4'])
    a('ori 0, 3, 4', ['R3'])
    a('oris 3, 4, 5', ['R4'])
    a('oris 3, 4, 7', ['R4'])
    a('oris 0, 3, 4', ['R3'])
    a('xori 3, 4, 5', ['R4'])
    a('xori 3, 4, 7', ['R4'])
    a('xori 3, 4, 0x1234', ['R4'])
    a('xori 0, 3, 4', ['R3'])
    a('xoris 3, 4, 5', ['R4'])
    a('xoris 3, 4, 7', ['R4'])
    a('xoris 0, 3, 4', ['R3'])
    a('mullw 3, 4, 7', ['R4'])
    a('mullw 0, 3, 4', ['R3', 'R4'])
    a('mulhw 3, 4, 7', ['R4'])
    a('mulhw 0, 3, 4', ['R3', 'R4'])
    a('mulhwu 3, 4, 7', ['R4'])
    a('mulhwu 0, 3, 4', ['R3', 'R4'])
    a('mulli 3, 4, 5', ['R4'])
    a('mulli 3, 4, 7', ['R4'])
    a('mulli 3, 4, 0x1234', ['R4'])
    a('mulli 0, 3, 4', ['R3'])
    a('slw 3, 4, 7', ['R4'])
    a('slw 0, 3, 4', ['R4', 'R3'])
    a('srw 3, 4, 7', ['R4'])
    a('srw 0, 3, 4', ['R4', 'R3'])
    a('sraw 3, 4, 7', ['R4'])
    a('sraw 0, 3, 4', ['R4', 'R3'])
    a('srawi 3, 4, 5', ['R4'])
    a('srawi 0, 3, 4', ['R3'])
    a('rlwinm 3, 4, 5, 0, 31', ['R4'])
    a('rlwinm 3, 4, 7, 0, 31', ['R4'])
    a('rlwinm 3, 4, 5, 6', ['R4'])
    a('rlwnm 3, 4, 5, 0, 31', ['R5', 'R4'])
    a('rlwnm 3, 4, 7, 0, 31', ['R4'])
    a('rlwnm 3, 4, 5, 6', ['R5', 'R4'])
    a('rlwimi 3, 4, 5, 0, 31', ['R4', 'R3'])
    a('rlwimi 3, 4, 7, 0, 31', ['R4', 'R3'])
    a('rlwimi 3, 4, 5, 6', ['R4', 'R3'])
    a('cmpw 3, 4, 5', ['R4', 'R5'])
    a('cmpw 3, 4', ['R3', 'R4'])
    a('cmpw 3, 4, 7', ['R4'])
    a('cmpwi 3, 4, 5', ['R4'])
    a('cmpwi 3, 4', ['R3'])
    a('cmpwi 3, 4, 7', ['R4'])
    a('cmpwi 3, 4, 0x1234', ['R4'])
    a('cmplw 3, 4, 5', ['R4', 'R5'])
    a('cmplw 3, 4', ['R3', 'R4'])
    a('cmplw 3, 4, 7', ['R4'])
    a('cmplwi 3, 4, 5', ['R4'])
    a('cmplwi 3, 4', ['R3'])
    a('cmplwi 3, 4, 7', ['R4'])
    a('cmplwi 3, 4, 0x1234', ['R4'])
    # --- July 23 campaign (batch 2): capped register variants + memory-operand shapes ---
    a('add 3, 4, 0', ['R4'])
    a('add 3, 4, 15', ['R4'])
    a('add 5, 6, 7', ['R6'])
    a('addc 3, 4, 0', ['R4'])
    a('addc 3, 4, 15', ['R4'])
    a('addc 5, 6, 7', ['R6'])
    a('subf 3, 4, 0', ['R4'])
    a('subf 3, 4, 15', ['R4'])
    a('subf 5, 6, 7', ['R6'])
    a('subfc 3, 4, 0', ['R4'])
    a('subfc 3, 4, 15', ['R4'])
    a('subfc 5, 6, 7', ['R6'])
    a('subfic 3, 4, 0', ['R4'])
    a('subfic 3, 4, 0x7fff', ['R4'])
    a('subfic 3, 4, -1', ['R4'])
    a('subfic 3, 4, 15', ['R4'])
    a('subfic 5, 6, 7', ['R6'])
    a('addi 3, 4, 0', ['R4'])
    a('addi 3, 4, 0x7fff', ['R4'])
    a('addi 3, 4, -1', ['R4'])
    a('addi 3, 4, 15', ['R4'])
    a('addi 5, 6, 7', ['R6'])
    a('addis 3, 4, 0', ['R4'])
    a('addis 3, 4, 0x7fff', ['R4'])
    a('addis 3, 4, -1', ['R4'])
    a('addis 3, 4, 15', ['R4'])
    a('addis 5, 6, 7', ['R6'])
    a('addic 3, 4, 0', ['R4'])
    a('addic 3, 4, 0x7fff', ['R4'])
    a('addic 3, 4, -1', ['R4'])
    a('addic 3, 4, 15', ['R4'])
    a('addic 5, 6, 7', ['R6'])
    a('and 3, 4, 0', ['R4'])
    a('and 3, 4, 15', ['R4'])
    a('and 5, 6, 7', ['R6'])
    a('andc 3, 4, 0', ['R4'])
    a('andc 3, 4, 15', ['R4'])
    a('andc 5, 6, 7', ['R6'])
    a('or 3, 4, 0', ['R4'])
    a('or 3, 4, 15', ['R4'])
    a('or 5, 6, 7', ['R6'])
    a('orc 3, 4, 0', ['R4'])
    a('orc 3, 4, 15', ['R4'])
    a('orc 5, 6, 7', ['R6'])
    a('xor 3, 4, 0', ['R4'])
    a('xor 3, 4, 15', ['R4'])
    a('xor 5, 6, 7', ['R6'])
    a('nand 3, 4, 0', ['R4'])
    a('nand 3, 4, 15', ['R4'])
    a('nand 5, 6, 7', ['R6'])
    a('nor 3, 4, 0', ['R4'])
    a('nor 3, 4, 15', ['R4'])
    a('nor 5, 6, 7', ['R6'])
    a('eqv 3, 4, 0', ['R4'])
    a('eqv 3, 4, 15', ['R4'])
    a('eqv 5, 6, 7', ['R6'])
    a('andi. 3, 4, 0', ['R4', 'cr0'])
    a('andi. 3, 4, 0x7fff', ['R4', 'cr0'])
    a('andi. 6, 7, 8', ['cr0'])
    a('andi. 3, 4, 15', ['R4', 'cr0'])
    a('andi. 5, 6, 7', ['R6', 'cr0'])
    a('andis. 3, 4, 0', ['R4', 'cr0'])
    a('andis. 3, 4, 0x7fff', ['R4', 'cr0'])
    a('andis. 6, 7, 8', ['cr0'])
    a('andis. 3, 4, 15', ['R4', 'cr0'])
    a('andis. 5, 6, 7', ['R6', 'cr0'])
    a('ori 3, 4, 0', ['R4'])
    a('ori 3, 4, 0x7fff', ['R4'])
    a('ori 3, 4, 15', ['R4'])
    a('ori 5, 6, 7', ['R6'])
    a('oris 3, 4, 0', ['R4'])
    a('oris 3, 4, 0x7fff', ['R4'])
    a('oris 3, 4, 15', ['R4'])
    a('oris 5, 6, 7', ['R6'])
    a('xori 3, 4, 0', ['R4'])
    a('xori 3, 4, 0x7fff', ['R4'])
    a('xori 3, 4, 15', ['R4'])
    a('xori 5, 6, 7', ['R6'])
    a('xoris 3, 4, 0', ['R4'])
    a('xoris 3, 4, 0x7fff', ['R4'])
    a('xoris 3, 4, 15', ['R4'])
    a('xoris 5, 6, 7', ['R6'])
    a('mullw 3, 4, 0', ['R4'])
    a('mullw 3, 4, 15', ['R4'])
    a('mullw 5, 6, 7', ['R6'])
    a('mulhw 3, 4, 0', ['R4'])
    a('mulhw 3, 4, 15', ['R4'])
    a('mulhw 5, 6, 7', ['R6'])
    a('mulhwu 3, 4, 0', ['R4'])
    a('mulhwu 3, 4, 15', ['R4'])
    a('mulhwu 5, 6, 7', ['R6'])
    a('mulli 3, 4, 0', ['R4'])
    a('mulli 3, 4, 0x7fff', ['R4'])
    a('mulli 3, 4, -1', ['R4'])
    a('mulli 3, 4, 15', ['R4'])
    a('mulli 5, 6, 7', ['R6'])
    a('slw 3, 4, 0', ['R4'])
    a('slw 3, 4, 15', ['R4'])
    a('slw 5, 6, 7', ['R6'])
    a('srw 3, 4, 0', ['R4'])
    a('srw 3, 4, 15', ['R4'])
    a('srw 5, 6, 7', ['R6'])
    a('sraw 3, 4, 0', ['R4'])
    a('sraw 3, 4, 15', ['R4'])
    a('sraw 5, 6, 7', ['R6'])
    a('srawi 3, 4, 0', ['R4'])
    a('srawi 3, 4, 15', ['R4'])
    a('srawi 5, 6, 7', ['R6'])
    a('rlwinm 3, 4, 5, 0, 15', ['R4'])
    a('rlwinm 3, 4, 5, 8, 23', ['R4'])
    a('rlwinm 3, 4, 5, 16, 31', ['R4'])
    a('rlwinm 3, 4, 4, 28, 31', ['R4'])
    a('rlwinm 3, 4, 1, 0, 31', ['R4'])
    a('rlwnm 3, 4, 5, 0, 15', ['R5', 'R4'])
    a('rlwnm 3, 4, 5, 8, 23', ['R5', 'R4'])
    a('rlwnm 3, 4, 5, 16, 31', ['R5', 'R4'])
    a('rlwnm 3, 4, 4, 28, 31', ['R4'])
    a('rlwnm 3, 4, 1, 0, 31', ['R4'])
    a('rlwimi 3, 4, 5, 0, 15', ['R4', 'R3'])
    a('rlwimi 3, 4, 5, 8, 23', ['R4', 'R3'])
    a('rlwimi 3, 4, 5, 16, 31', ['R4', 'R3'])
    a('rlwimi 3, 4, 4, 28, 31', ['R4', 'R3'])
    a('rlwimi 3, 4, 1, 0, 31', ['R4', 'R3'])
    a('cmpw 3, 4, 0', ['R4'])
    a('cmpw 3, 4, 15', ['R4'])
    a('cmpw 5, 6, 7', ['R6'])
    a('cmpwi 3, 4, 0', ['R4'])
    a('cmpwi 3, 4, 0x7fff', ['R4'])
    a('cmpwi 3, 4, -1', ['R4'])
    a('cmpwi 3, 4, 15', ['R4'])
    a('cmpwi 5, 6, 7', ['R6'])
    a('cmplw 3, 4, 0', ['R4'])
    a('cmplw 3, 4, 15', ['R4'])
    a('cmplw 5, 6, 7', ['R6'])
    a('cmplwi 3, 4, 0', ['R4'])
    a('cmplwi 3, 4, 0x7fff', ['R4'])
    a('cmplwi 3, 4, 15', ['R4'])
    a('cmplwi 5, 6, 7', ['R6'])
    a('stw 4, -8(1); lwz 3, -8(1)', ['R4'])
    a('stb 4, -8(1); lbz 3, -8(1)', ['R4'])
    a('sth 4, -8(1); lhz 3, -8(1)', ['R4'])
    return c


def _riscv(isa):
    # hand-assembled RV64 (rd=t0=5, rs1=t1=6, rs2=t2=7, t3=28); no keystone, no flags.
    def rt(f7, rs2, rs1, f3, rd, op):
        return ((f7 << 25) | (rs2 << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | op).to_bytes(4, 'little').hex()

    def it(imm, rs1, f3, rd, op):
        return (((imm & 0xFFF) << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | op).to_bytes(4, 'little').hex()

    def ut(imm20, rd, op):
        return (((imm20 & 0xFFFFF) << 12) | (rd << 7) | op).to_bytes(4, 'little').hex()

    R, W, I, IW, U, AUI = 0x33, 0x3B, 0x13, 0x1B, 0x37, 0x17  # noqa: E741
    c = []
    # register-register: base, M-extension multiply AND divide, and the W forms
    rr = {
        'add': rt(0, 7, 6, 0, 5, R), 'sub': rt(0x20, 7, 6, 0, 5, R), 'sll': rt(0, 7, 6, 1, 5, R),
        'slt': rt(0, 7, 6, 2, 5, R), 'sltu': rt(0, 7, 6, 3, 5, R), 'xor': rt(0, 7, 6, 4, 5, R),
        'srl': rt(0, 7, 6, 5, 5, R), 'sra': rt(0x20, 7, 6, 5, 5, R), 'or': rt(0, 7, 6, 6, 5, R),
        'and': rt(0, 7, 6, 7, 5, R), 'mul': rt(1, 7, 6, 0, 5, R), 'mulh': rt(1, 7, 6, 1, 5, R),
        'mulhu': rt(1, 7, 6, 3, 5, R), 'mulhsu': rt(1, 7, 6, 2, 5, R),
        'addw': rt(0, 7, 6, 0, 5, W), 'subw': rt(0x20, 7, 6, 0, 5, W), 'sllw': rt(0, 7, 6, 1, 5, W),
        'srlw': rt(0, 7, 6, 5, 5, W), 'sraw': rt(0x20, 7, 6, 5, 5, W), 'mulw': rt(1, 7, 6, 0, 5, W),
    }
    for m, hx in rr.items():
        c.append((m, hx, ['t1', 't2'], {}))
    # divide / remainder: the divisor must be non-zero at every point of the cube
    dv = {
        'div': rt(1, 7, 6, 4, 5, R), 'divu': rt(1, 7, 6, 5, 5, R),
        'rem': rt(1, 7, 6, 6, 5, R), 'remu': rt(1, 7, 6, 7, 5, R),
        'divw': rt(1, 7, 6, 4, 5, W), 'divuw': rt(1, 7, 6, 5, 5, W),
        'remw': rt(1, 7, 6, 6, 5, W), 'remuw': rt(1, 7, 6, 7, 5, W),
    }
    for m, hx in dv.items():
        c.append((m, hx, ['t1'], {'t2': 'nonzero'}))
    # register-immediate
    ri = {
        'addi': it(5, 6, 0, 5, I), 'addi_neg': it(-5, 6, 0, 5, I),
        'slti': it(7, 6, 2, 5, I), 'sltiu': it(7, 6, 3, 5, I),
        'xori': it(0xFFF, 6, 4, 5, I), 'ori': it(0xF, 6, 6, 5, I), 'andi': it(0xF, 6, 7, 5, I),
        'slli': it(4, 6, 1, 5, I), 'srli': it(4, 6, 5, 5, I), 'srai': it((0x10 << 6) | 4, 6, 5, 5, I),
        'slli_31': it(31, 6, 1, 5, I), 'srai_63': it((0x10 << 6) | 63, 6, 5, 5, I),
        'addiw': it(5, 6, 0, 5, IW), 'slliw': it(4, 6, 1, 5, IW),
        'srliw': it(4, 6, 5, 5, IW), 'sraiw': it((0x20 << 5) | 4, 6, 5, 5, IW),
    }
    for m, hx in ri.items():
        c.append((m, hx, ['t1'], {}))
    # upper-immediate forms read no register at all -- they check that a constant
    # result is reported as untainted rather than inheriting anything.
    c.append(('lui', ut(0x12345, 5, U), [], {}))
    c.append(('auipc', ut(0x12345, 5, AUI), [], {}))
    return c


def _x86(isa):
    c = []

    def a(asm, srcs, cons=None):
        c.append((asm, asm, srcs, cons or {}))

    FL = ['CF', 'ZF', 'SF', 'OF', 'PF']
    # --- 64-bit register-register ---
    for m in ('add', 'sub', 'and', 'or', 'xor', 'cmp', 'test'):
        a(f'{m} rax, rbx', ['RAX', 'RBX'])
    a('adc rax, rbx', ['RAX', 'RBX', 'CF'])
    a('sbb rax, rbx', ['RAX', 'RBX', 'CF'])
    a('neg rax', ['RAX'])
    a('not rax', ['RAX'])
    a('inc rax', ['RAX'])
    a('dec rax', ['RAX'])
    a('xchg rax, rbx', ['RAX', 'RBX'])
    # --- immediate forms ---
    a('add rax, 1365', ['RAX'])
    a('sub rax, 1365', ['RAX'])
    a('and rax, 0xff0f', ['RAX'])
    a('or rax, 0x0ff0', ['RAX'])
    a('xor rax, 0xf00f', ['RAX'])
    a('cmp rax, 1365', ['RAX'])
    a('adc rax, 1365', ['RAX', 'CF'])
    # --- sub-register widths: a narrow write must PRESERVE the upper bits' taint ---
    for m in ('add', 'sub', 'and', 'or', 'xor'):
        a(f'{m} eax, ebx', ['RAX', 'RBX'])
    a('add ax, bx', ['RAX', 'RBX'])
    a('sub ax, bx', ['RAX', 'RBX'])
    a('add al, bl', ['RAX', 'RBX'])
    a('xor al, bl', ['RAX', 'RBX'])
    a('and ah, bh', ['RAX', 'RBX'])
    a('neg al', ['RAX'])
    a('inc al', ['RAX'])
    a('mov al, bl', ['RAX', 'RBX'])
    a('mov eax, ebx', ['RAX', 'RBX'])            # 32-bit move ZERO-extends
    # --- shifts / rotates, by immediate and by CL ---
    for m in ('shl', 'shr', 'sar', 'rol', 'ror'):
        a(f'{m} rax, 7', ['RAX'])
        # OF is architecturally UNDEFINED for any shift count but 1.  With a
        # register count that cannot be decided statically, so the
        # identity-preserve detector (which handles `shl rax,7`) cannot fold it and
        # the oracle reports Unicorn's invented value as taint the engine must not
        # model.  Rather than hide the flag, OF is dropped HERE and the DEFINED
        # case is tested by the pinned-count entries below.
        a(f'{m} rax, cl', ['RAX', 'RCX'], {'exclude_flags': ['OF']})
        # count == 1: OF is DEFINED, so it stays checked.
        c.append((f'{m} rax, cl [cl=1]', f'{m} rax, cl', ['RAX'], {'RCX': 1}))
    # 1-bit shifts: OF is DEFINED for count 1 (undefined only for other counts).
    #   SHL: OF = MSB(result) XOR CF   -- SLEIGH emits exactly this, so it is kept.
    #   SAR: OF = 0                    -- correct.
    #   SHR: OF = MSB of the ORIGINAL operand -- SLEIGH emits `OF = 0x0`, which is
    #        WRONG.  Verified on Unicorn: RAX MSB=1 gives OF=1, MSB=0 gives OF=0,
    #        deterministically.  `shr rax,1` is therefore EXCLUDED as a SLEIGH
    #        modelling bug, not an engine gap (27 spurious under-taints).
    a('shl rax, 1', ['RAX'])
    a('sar rax, 1', ['RAX'])
    a('rcl rax, 1', ['RAX', 'CF'])               # rotate THROUGH carry
    a('rcr rax, 1', ['RAX', 'CF'])
    a('shld rax, rbx, 7', ['RAX', 'RBX'])        # double-precision shifts
    a('shrd rax, rbx, 7', ['RAX', 'RBX'])
    a('shl eax, 7', ['RAX'])
    a('sar eax, 7', ['RAX'])
    # --- bit test / scan / count ---
    a('bt rax, rbx', ['RAX', 'RBX'])             # data-dependent bit SELECT -> CF
    a('bts rax, rbx', ['RAX', 'RBX'])
    a('btr rax, rbx', ['RAX', 'RBX'])
    a('btc rax, rbx', ['RAX', 'RBX'])
    a('bt rax, 37', ['RAX'])
    a('bsf rax, rbx', ['RBX'])
    a('bsr rax, rbx', ['RBX'])
    a('popcnt rax, rbx', ['RBX'])
    a('bswap rax', ['RAX'])
    # --- multiply (incl. the multi-output RDX:RAX form) ---
    a('imul rax, rbx', ['RAX', 'RBX'])
    a('imul rax, rbx, 1365', ['RBX'])
    a('mul rbx', ['RAX', 'RBX'])                 # writes RDX:RAX
    a('imul rbx', ['RAX', 'RBX'])                # writes RDX:RAX
    a('mul ebx', ['RAX', 'RBX'])
    a('cqo', ['RAX'])                            # sign-extend RAX into RDX
    a('cdq', ['RAX'])
    # --- conditional moves and sets (flag consumers) ---
    for cc in ('e', 'ne', 'l', 'g', 'b', 'a', 's', 'o'):
        a(f'set{cc} al', FL)
    for cc in ('e', 'ne', 'l', 'a'):
        a(f'cmov{cc} rax, rbx', ['RAX', 'RBX'] + FL)
    # --- extension / address arithmetic ---
    a('movzx rax, bx', ['RBX'])
    a('movsx rax, bx', ['RBX'])
    a('movzx rax, bl', ['RBX'])
    a('movsx rax, bl', ['RBX'])
    a('movsxd rax, ebx', ['RBX'])
    a('lea rax, [rbx + rcx*4 + 8]', ['RBX', 'RCX'])  # ALU work, no memory access
    a('lea eax, [ebx + ecx*8]', ['RBX', 'RCX'])
    # --- memory ROUND TRIPS -------------------------------------------------
    # Only push/operate/pop shapes, with the stack pointer PINNED and untainted.
    # A tainted ADDRESS is deliberately out of scope: there is no unified memory
    # model here, so a read or write referenced by tainted data cannot be
    # ground-truthed.  These exercise the STORE -> LOAD taint path only.
    a('push rax; pop rbx', ['RAX'])
    a('push rax; pop rax', ['RAX'])
    a('push rax; push rbx; pop rcx; pop rdx', ['RAX', 'RBX'])
    a('push rax; add qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; xor qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; and qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; shl qword ptr [rsp], 7; pop rcx', ['RAX'])
    a('push rax; not qword ptr [rsp]; pop rcx', ['RAX'])
    a('push rax; neg qword ptr [rsp]; pop rcx', ['RAX'])
    a('push rax; inc qword ptr [rsp]; pop rcx', ['RAX'])
    # --- further integer coverage -------------------------------------------
    a('adc eax, ebx', ['RAX', 'RBX', 'CF'])
    a('sbb eax, ebx', ['RAX', 'RBX', 'CF'])
    a('imul eax, ebx', ['RAX', 'RBX'])
    a('bt eax, ebx', ['RAX', 'RBX'])
    # SHLD/SHRD leave OF UNDEFINED for any count but 1 (Intel SDM), and the count
    # is a runtime value here, so the same exclusion as the shift-by-CL forms
    # applies.  Confirmed from the failing records: RCX's tainted bits all lay
    # OUTSIDE `CL & 0x3f`, so the amount was fixed and != 1.
    a('shld rax, rbx, cl', ['RAX', 'RBX', 'RCX'], {'exclude_flags': ['OF']})
    a('shrd rax, rbx, cl', ['RAX', 'RBX', 'RCX'], {'exclude_flags': ['OF']})
    c.append(('shld rax, rbx, cl [cl=1]', 'shld rax, rbx, cl', ['RAX', 'RBX'], {'RCX': 1}))
    c.append(('shrd rax, rbx, cl [cl=1]', 'shrd rax, rbx, cl', ['RAX', 'RBX'], {'RCX': 1}))
    a('cmovs rax, rbx', ['RAX', 'RBX'] + FL)
    a('cmovo rax, rbx', ['RAX', 'RBX'] + FL)
    a('setle al', FL)
    a('setge al', FL)
    a('seta bl', FL)
    a('test al, bl', ['RAX', 'RBX'])
    a('xchg eax, ebx', ['RAX', 'RBX'])
    a('bswap eax', ['RAX'])
    a('movsx eax, bl', ['RBX'])
    a('rol eax, cl', ['RAX', 'RCX'], {'exclude_flags': ['OF']})
    c.append(('rol eax, cl [cl=1]', 'rol eax, cl', ['RAX'], {'RCX': 1}))
    a('sar rax, 63', ['RAX'])
    a('shl rax, 63', ['RAX'])
    # --- BMI1/BMI2 (flagless bit ops and shifts), extended carry, acc extend ---
    a('andn rax, rbx, rcx', ['RBX', 'RCX'])
    a('blsi rax, rbx', ['RBX'])
    a('blsr rax, rbx', ['RBX'])
    a('blsmsk rax, rbx', ['RBX'])
    a('tzcnt rax, rbx', ['RBX'])
    a('lzcnt rax, rbx', ['RBX'])
    a('sarx rax, rbx, rcx', ['RBX', 'RCX'])   # variable shift, NO flags written
    a('shlx rax, rbx, rcx', ['RBX', 'RCX'])
    a('shrx rax, rbx, rcx', ['RBX', 'RCX'])
    a('mulx rax, rbx, rcx', ['RDX', 'RCX'])   # RDX * RCX -> RAX:RBX
    a('rorx rax, rbx, 7', ['RBX'])            # rotate, NO flags
    a('adcx rax, rbx', ['RAX', 'RBX', 'CF'])  # add-with-carry, updates ONLY CF
    a('adox rax, rbx', ['RAX', 'RBX', 'OF'])  # add-with-overflow, updates ONLY OF
    a('cbw', ['RAX'])                         # sign-extend AL -> AX
    a('cwde', ['RAX'])                        # sign-extend AX -> EAX (zero-extends to RAX)
    a('cdqe', ['RAX'])                        # sign-extend EAX -> RAX
    a('xadd rax, rbx', ['RAX', 'RBX'])        # exchange-and-add
    a('sahf', ['RAX'])                        # AH -> flags
    a('lahf', ['CF', 'PF', 'ZF', 'SF'])       # flags -> AH
    a('push rax; xadd qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    # --- July 23 campaign: verified-sound enumerated instructions ---
    a('add rax, 1', ['RAX'])
    a('adc ax, bx', ['CF', 'RAX', 'RBX'])
    a('adc al, bl', ['CF', 'RAX', 'RBX'])
    a('adc rax, 1', ['CF', 'RAX'])
    a('sub al, bl', ['RAX', 'RBX'])
    a('sub rax, 1', ['RAX'])
    a('sbb ax, bx', ['CF', 'RAX', 'RBX'])
    a('sbb al, bl', ['CF', 'RAX', 'RBX'])
    a('sbb rax, 1', ['CF', 'RAX'])
    a('and ax, bx', ['RAX', 'RBX'])
    a('and al, bl', ['RAX', 'RBX'])
    a('and rax, 1', ['RAX'])
    a('or ax, bx', ['RAX', 'RBX'])
    a('or al, bl', ['RAX', 'RBX'])
    a('or rax, 1', ['RAX'])
    a('xor ax, bx', ['RAX', 'RBX'])
    a('xor rax, 1', ['RAX'])
    a('cmp eax, ebx', ['RAX', 'RBX'])
    a('cmp ax, bx', ['RAX', 'RBX'])
    a('cmp al, bl', ['RAX', 'RBX'])
    a('cmp rax, 1', ['RAX'])
    a('test eax, ebx', ['RAX', 'RBX'])
    a('test ax, bx', ['RAX', 'RBX'])
    a('test rax, 1', ['RAX'])
    a('inc eax', ['RAX'])
    a('inc rbx', ['RBX'])
    a('inc ebx', ['RBX'])
    a('dec eax', ['RAX'])
    a('dec al', ['RAX'])
    a('dec rbx', ['RBX'])
    a('dec ebx', ['RBX'])
    a('neg eax', ['RAX'])
    a('neg rbx', ['RBX'])
    a('neg ebx', ['RBX'])
    a('not eax', ['RAX'])
    a('not al', ['RAX'])
    a('not rbx', ['RBX'])
    a('not ebx', ['RBX'])
    a('mul rax', ['RAX'])
    a('mul eax', ['RAX'])
    a('mul al', ['RAX'])
    a('imul ax, bx', ['RAX', 'RBX'])
    a('imul rax, 1', ['RAX'])
    a('imul rax, rbx, 7', ['RBX'])
    a('shl eax', ['RAX'])
    a('shl al', ['RAX'])
    a('shl rbx', ['RBX'])
    a('sar eax', ['RAX'])
    a('sar al', ['RAX'])
    a('sar rbx', ['RBX'])
    a('sal ebx', ['RBX'])
    a('rol rax, 1', ['RAX'])
    a('rol eax', ['RAX'])
    a('rol al', ['RAX'])
    a('rol rbx', ['RBX'])
    a('ror rax, 1', ['RAX'])
    a('ror eax', ['RAX'])
    a('ror al', ['RAX'])
    a('ror rbx', ['RBX'])
    a('rcl rax, cl', ['RCX', 'RAX', 'CF'])
    a('rcl eax', ['CF', 'RAX'])
    a('rcl al', ['CF', 'RAX'])
    a('rcl rbx', ['CF', 'RBX'])
    a('rcr rax, cl', ['RCX', 'RAX', 'CF'])
    a('rcr eax', ['CF', 'RAX'])
    a('rcr al', ['CF', 'RAX'])
    a('rcr rbx', ['CF', 'RBX'])
    a('bt ax, bx', ['RBX', 'RAX'])
    a('bt rax, 1', ['RAX'])
    a('bts eax, ebx', ['RBX', 'RAX'])
    a('bts ax, bx', ['RBX', 'RAX'])
    a('bts rax, 1', ['RAX'])
    a('btr eax, ebx', ['RBX', 'RAX'])
    a('btr ax, bx', ['RBX', 'RAX'])
    a('btr rax, 1', ['RAX'])
    a('btc eax, ebx', ['RBX', 'RAX'])
    a('btc ax, bx', ['RBX', 'RAX'])
    a('btc rax, 1', ['RAX'])
    a('tzcnt eax, ebx', ['RBX'])
    a('tzcnt ax, bx', ['RBX'])
    a('lzcnt eax, ebx', ['RBX'])
    a('lzcnt ax, bx', ['RBX'])
    a('popcnt eax, ebx', ['RBX'])
    a('popcnt ax, bx', ['RBX'])
    a('movzx rax, cl', ['RCX'])
    a('movzx eax, bl', ['RBX'])
    a('movsx rax, cl', ['RCX'])
    a('xchg ax, bx', ['RAX', 'RBX'])
    a('xchg al, bl', ['RAX', 'RBX'])
    a('xadd eax, ebx', ['RAX', 'RBX'])
    a('xadd ax, bx', ['RAX', 'RBX'])
    a('xadd al, bl', ['RAX', 'RBX'])
    a('bswap rbx', ['RBX'])
    a('bswap ebx', ['RBX'])
    a('cwd', ['RAX'])
    a('setno al', ['OF'])
    a('setae al', ['CF'])
    a('setbe al', ['CF', 'ZF'])
    a('setns al', ['SF'])
    a('setp al', ['PF'])
    a('setnp al', ['PF'])
    a('cmovo eax, ebx', ['RBX', 'RAX', 'OF'])
    a('cmovo ax, bx', ['RBX', 'OF'])
    a('cmovno rax, rbx', ['OF', 'RBX'])
    a('cmovno eax, ebx', ['OF', 'RBX', 'RAX'])
    a('cmovno ax, bx', ['OF', 'RBX'])
    a('cmovb rax, rbx', ['RBX', 'CF'])
    a('cmovb eax, ebx', ['RBX', 'RAX', 'CF'])
    a('cmovb ax, bx', ['RBX', 'CF'])
    a('cmovae rax, rbx', ['CF', 'RBX'])
    a('cmovae eax, ebx', ['CF', 'RBX', 'RAX'])
    a('cmovae ax, bx', ['CF', 'RBX'])
    a('cmove eax, ebx', ['RBX', 'RAX', 'ZF'])
    a('cmove ax, bx', ['RBX', 'ZF'])
    a('cmovne eax, ebx', ['ZF', 'RBX', 'RAX'])
    a('cmovne ax, bx', ['ZF', 'RBX'])
    a('cmovbe rax, rbx', ['CF', 'ZF', 'RBX'])
    a('cmovbe eax, ebx', ['CF', 'ZF', 'RBX', 'RAX'])
    a('cmovbe ax, bx', ['CF', 'ZF', 'RBX'])
    a('cmova eax, ebx', ['CF', 'ZF', 'RBX', 'RAX'])
    a('cmova ax, bx', ['CF', 'ZF', 'RBX'])
    a('cmovs eax, ebx', ['RBX', 'RAX', 'SF'])
    a('cmovs ax, bx', ['RBX', 'SF'])
    a('cmovns rax, rbx', ['SF', 'RBX'])
    a('cmovns eax, ebx', ['SF', 'RBX', 'RAX'])
    a('cmovns ax, bx', ['SF', 'RBX'])
    a('cmovl eax, ebx', ['OF', 'SF', 'RBX', 'RAX'])
    a('cmovl ax, bx', ['OF', 'SF', 'RBX'])
    a('cmovge rax, rbx', ['OF', 'SF', 'RBX'])
    a('cmovge eax, ebx', ['OF', 'SF', 'RBX', 'RAX'])
    a('cmovge ax, bx', ['OF', 'SF', 'RBX'])
    a('cmovle rax, rbx', ['OF', 'SF', 'ZF', 'RBX'])
    a('cmovle eax, ebx', ['OF', 'SF', 'ZF', 'RBX', 'RAX'])
    a('cmovle ax, bx', ['OF', 'SF', 'ZF', 'RBX'])
    a('cmovg rax, rbx', ['ZF', 'OF', 'SF', 'RBX'])
    a('cmovg eax, ebx', ['ZF', 'OF', 'SF', 'RBX', 'RAX'])
    a('cmovg ax, bx', ['ZF', 'OF', 'SF', 'RBX'])
    a('andn eax, ebx, ecx', ['RBX', 'RCX'])
    a('bextr rax, rbx, rcx', ['RBX', 'RCX'])
    a('blsi eax, ebx', ['RBX'])
    a('blsr eax, ebx', ['RBX'])
    a('blsmsk eax, ebx', ['RBX'])
    a('bzhi rax, rbx, rcx', ['RCX', 'RBX'])
    a('bzhi eax, ebx, ecx', ['RCX', 'RBX'])
    a('mulx eax, ebx, ecx', ['RDX', 'RCX'])
    a('sarx eax, ebx, ecx', ['RCX', 'RBX'])
    a('shlx eax, ebx, ecx', ['RCX', 'RBX'])
    a('shrx eax, ebx, ecx', ['RCX', 'RBX'])
    a('adcx eax, ebx', ['RAX', 'RBX', 'CF'])
    a('adox eax, ebx', ['RAX', 'RBX', 'OF'])
    a('crc32 rax, rbx', ['RAX', 'RBX'])
    a('crc32 eax, ebx', ['RAX', 'RBX'])
    a('crc32 rax, cl', ['RAX', 'RCX'])
    a('crc32 eax, bl', ['RAX', 'RBX'])
    # --- July 23 campaign (batch 2): capped register variants + memory-operand shapes ---
    a('add rax, 0x7f', ['RAX'])
    a('add rax, 0x7fffffff', ['RAX'])
    a('add eax, 0xffff', ['RAX'])
    a('add ax, 0x7f', ['RAX'])
    a('add rax, 3', ['RAX'])
    a('add rax, 15', ['RAX'])
    a('adc r8, r9', ['CF'])
    a('adc r10d, r11d', ['CF'])
    a('adc r12w, r13w', ['CF'])
    a('adc r14b, r15b', ['CF'])
    a('adc rax, 0x7f', ['CF', 'RAX'])
    a('adc rax, 0x7fffffff', ['CF', 'RAX'])
    a('sub rax, 0x7f', ['RAX'])
    a('sub rax, 0x7fffffff', ['RAX'])
    a('sub eax, 0xffff', ['RAX'])
    a('sub ax, 0x7f', ['RAX'])
    a('sub rax, 3', ['RAX'])
    a('sub rax, 15', ['RAX'])
    a('sbb r8, r9', ['CF'])
    a('sbb r10d, r11d', ['CF'])
    a('sbb r12w, r13w', ['CF'])
    a('sbb r14b, r15b', ['CF'])
    a('sbb rax, 0x7f', ['CF', 'RAX'])
    a('sbb rax, 0x7fffffff', ['CF', 'RAX'])
    a('and rax, 0x7f', ['RAX'])
    a('and rax, 0x7fffffff', ['RAX'])
    a('and eax, 0xffff', ['RAX'])
    a('and ax, 0x7f', ['RAX'])
    a('and rax, 3', ['RAX'])
    a('and rax, 15', ['RAX'])
    a('or rax, 0x7f', ['RAX'])
    a('or rax, 0x7fffffff', ['RAX'])
    a('or eax, 0xffff', ['RAX'])
    a('or ax, 0x7f', ['RAX'])
    a('or rax, 3', ['RAX'])
    a('or rax, 15', ['RAX'])
    a('xor rax, 0x7f', ['RAX'])
    a('xor rax, 0x7fffffff', ['RAX'])
    a('xor eax, 0xffff', ['RAX'])
    a('xor ax, 0x7f', ['RAX'])
    a('xor rax, 3', ['RAX'])
    a('xor rax, 15', ['RAX'])
    a('cmp rax, 0x7f', ['RAX'])
    a('cmp rax, 0x7fffffff', ['RAX'])
    a('cmp eax, 0xffff', ['RAX'])
    a('cmp ax, 0x7f', ['RAX'])
    a('cmp rax, 3', ['RAX'])
    a('cmp rax, 15', ['RAX'])
    a('test rax, 0x7f', ['RAX'])
    a('test rax, 0x7fffffff', ['RAX'])
    a('test eax, 0xffff', ['RAX'])
    a('test ax, 0x7f', ['RAX'])
    a('test rax, 3', ['RAX'])
    a('test rax, 15', ['RAX'])
    a('mul r8', ['RAX'], {'exclude_flags': ['OF']})
    a('mul r8d', ['RAX'], {'exclude_flags': ['OF']})
    a('mul r8b', ['RAX'], {'exclude_flags': ['OF']})
    a('imul rax, 0x7f', ['RAX'], {'exclude_flags': ['OF']})
    a('imul rax, 0x7fffffff', ['RAX'], {'exclude_flags': ['OF']})
    a('imul eax, 0xffff', ['RAX'], {'exclude_flags': ['OF']})
    a('imul ax, 0x7f', ['RAX'], {'exclude_flags': ['OF']})
    a('imul rax, 3', ['RAX'], {'exclude_flags': ['OF']})
    a('imul rax, 15', ['RAX'], {'exclude_flags': ['OF']})
    a('shl rax, 0x7f', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shl ax, 0x7f', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shl rax, 3', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shl rax, 15', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shl rax, 31', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shl eax, 5', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shr rax, 0x7f', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shr ax, 0x7f', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shr rax, 3', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shr rax, 15', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shr rax, 31', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shr rax, 63', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('sar rax, 0x7f', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('sar ax, 0x7f', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('sar rax, 3', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('sar rax, 15', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('sar rax, 31', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('sar eax, 5', ['RAX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('rol rax, 0x7f', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('rol ax, 0x7f', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('rol rax, 3', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('rol rax, 15', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('rol rax, 31', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('rol rax, 63', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('ror rax, 0x7f', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('ror ax, 0x7f', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('ror rax, 3', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('ror rax, 15', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('ror rax, 31', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('ror rax, 63', ['RAX', 'CF', 'OF'], {'exclude_flags': ['OF']})
    a('rcl rax, 0x7f', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcl ax, 0x7f', ['CF', 'RAX'], {'exclude_flags': ['OF']})
    a('rcl rax, 3', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcl rax, 15', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcl rax, 31', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcl rax, 63', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcr rax, 0x7f', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcr ax, 0x7f', ['CF', 'RAX'], {'exclude_flags': ['OF']})
    a('rcr rax, 3', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcr rax, 15', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcr rax, 31', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('rcr rax, 63', ['RAX', 'CF'], {'exclude_flags': ['OF']})
    a('shld r8, r9', ['RCX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shld r10d, r11d', ['RCX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shld r12w, r13w', ['RCX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shld rax, rbx, 0x7f', ['RAX', 'RBX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shrd r8, r9', ['RCX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shrd r10d, r11d', ['RCX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shrd r12w, r13w', ['RCX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shrd rax, rbx, 0x7f', ['RAX', 'RBX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('shrd rbp, rsp', ['RCX', 'CF', 'OF', 'SF', 'ZF', 'PF'], {'exclude_flags': ['OF']})
    a('bt rax, 0x7f', ['RAX'])
    a('bt ax, 0x7f', ['RAX'])
    a('bt rax, 3', ['RAX'])
    a('bt rax, 15', ['RAX'])
    a('bt rax, 31', ['RAX'])
    a('bt rax, 63', ['RAX'])
    a('bts rax, 0x7f', ['RAX'])
    a('bts ax, 0x7f', ['RAX'])
    a('bts rax, 3', ['RAX'])
    a('bts rax, 15', ['RAX'])
    a('bts rax, 31', ['RAX'])
    a('bts rax, 63', ['RAX'])
    a('btr rax, 0x7f', ['RAX'])
    a('btr ax, 0x7f', ['RAX'])
    a('btr rax, 3', ['RAX'])
    a('btr rax, 15', ['RAX'])
    a('btr rax, 31', ['RAX'])
    a('btr rax, 63', ['RAX'])
    a('btc rax, 0x7f', ['RAX'])
    a('btc ax, 0x7f', ['RAX'])
    a('btc rax, 3', ['RAX'])
    a('btc rax, 15', ['RAX'])
    a('btc rax, 31', ['RAX'])
    a('btc rax, 63', ['RAX'])
    a('seto r8b', ['OF'])
    a('setno r8b', ['OF'])
    a('setb r8b', ['CF'])
    a('setae r8b', ['CF'])
    a('sete r8b', ['ZF'])
    a('setne r8b', ['ZF'])
    a('setbe r8b', ['CF', 'ZF'])
    a('seta r8b', ['CF', 'ZF'])
    a('sets r8b', ['SF'])
    a('setns r8b', ['SF'])
    a('setp r8b', ['PF'])
    a('setnp r8b', ['PF'])
    a('setl r8b', ['OF', 'SF'])
    a('setge r8b', ['OF', 'SF'])
    a('setle r8b', ['OF', 'SF', 'ZF'])
    a('setg r8b', ['ZF', 'OF', 'SF'])
    a('cmovo r8, r9', ['OF'])
    a('cmovo r10d, r11d', ['OF'])
    a('cmovo r12w, r13w', ['OF'])
    a('cmovo rbp, rsp', ['OF'])
    a('cmovno r8, r9', ['OF'])
    a('cmovno r10d, r11d', ['OF'])
    a('cmovno r12w, r13w', ['OF'])
    a('cmovno rbp, rsp', ['OF'])
    a('cmovb r8, r9', ['CF'])
    a('cmovb r10d, r11d', ['CF'])
    a('cmovb r12w, r13w', ['CF'])
    a('cmovb rbp, rsp', ['CF'])
    a('cmovae r8, r9', ['CF'])
    a('cmovae r10d, r11d', ['CF'])
    a('cmovae r12w, r13w', ['CF'])
    a('cmovae rbp, rsp', ['CF'])
    a('cmove r8, r9', ['ZF'])
    a('cmove r10d, r11d', ['ZF'])
    a('cmove r12w, r13w', ['ZF'])
    a('cmove rbp, rsp', ['ZF'])
    a('cmovne r8, r9', ['ZF'])
    a('cmovne r10d, r11d', ['ZF'])
    a('cmovne r12w, r13w', ['ZF'])
    a('cmovne rbp, rsp', ['ZF'])
    a('cmovbe r8, r9', ['CF', 'ZF'])
    a('cmovbe r10d, r11d', ['CF', 'ZF'])
    a('cmovbe r12w, r13w', ['CF', 'ZF'])
    a('cmovbe rbp, rsp', ['CF', 'ZF'])
    a('cmova r8, r9', ['CF', 'ZF'])
    a('cmova r10d, r11d', ['CF', 'ZF'])
    a('cmova r12w, r13w', ['CF', 'ZF'])
    a('cmova rbp, rsp', ['CF', 'ZF'])
    a('cmovs r8, r9', ['SF'])
    a('cmovs r10d, r11d', ['SF'])
    a('cmovs r12w, r13w', ['SF'])
    a('cmovs rbp, rsp', ['SF'])
    a('cmovns r8, r9', ['SF'])
    a('cmovns r10d, r11d', ['SF'])
    a('cmovns r12w, r13w', ['SF'])
    a('cmovns rbp, rsp', ['SF'])
    a('cmovl r8, r9', ['OF', 'SF'])
    a('cmovl r10d, r11d', ['OF', 'SF'])
    a('cmovl r12w, r13w', ['OF', 'SF'])
    a('cmovl rbp, rsp', ['OF', 'SF'])
    a('cmovge r8, r9', ['OF', 'SF'])
    a('cmovge r10d, r11d', ['OF', 'SF'])
    a('cmovge r12w, r13w', ['OF', 'SF'])
    a('cmovge rbp, rsp', ['OF', 'SF'])
    a('cmovle r8, r9', ['OF', 'SF', 'ZF'])
    a('cmovle r10d, r11d', ['OF', 'SF', 'ZF'])
    a('cmovle r12w, r13w', ['OF', 'SF', 'ZF'])
    a('cmovle rbp, rsp', ['OF', 'SF', 'ZF'])
    a('cmovg r8, r9', ['ZF', 'OF', 'SF'])
    a('cmovg r10d, r11d', ['ZF', 'OF', 'SF'])
    a('cmovg r12w, r13w', ['ZF', 'OF', 'SF'])
    a('cmovg rbp, rsp', ['ZF', 'OF', 'SF'])
    a('mulx r8, r9, r10', ['RDX'])
    a('rorx rax, rbx, 0x7f', ['RBX'])
    a('adcx r8, r9', ['CF'])
    a('adcx r10d, r11d', ['CF'])
    a('adcx rbp, rsp', ['CF'])
    a('adox r8, r9', ['OF'])
    a('adox r10d, r11d', ['OF'])
    a('adox rbp, rsp', ['OF'])
    a('crc32 rax, bl', ['RAX', 'RBX'])
    a('push rax; add qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; and qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; or qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; xor qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; adc qword ptr [rsp], rbx; pop rcx', ['RAX', 'CF', 'RBX'])
    a('push rax; xchg qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    a('push rax; add qword ptr [rsp], 0x33; pop rcx', ['RAX'])
    a('push rax; sub qword ptr [rsp], 0x33; pop rcx', ['RAX'])
    a('push rax; and qword ptr [rsp], 0x33; pop rcx', ['RAX'])
    a('push rax; or qword ptr [rsp], 0x33; pop rcx', ['RAX'])
    a('push rax; xor qword ptr [rsp], 0x33; pop rcx', ['RAX'])
    a('push rax; inc qword ptr [rsp]; pop rcx', ['RAX'])
    a('push rax; dec qword ptr [rsp]; pop rcx', ['RAX'])
    a('push rax; neg qword ptr [rsp]; pop rcx', ['RAX'])
    a('push rax; not qword ptr [rsp]; pop rcx', ['RAX'])
    a('mov [rsp-8], rax; mov rbx, [rsp-8]', ['RAX'])
    a('mov [rsp-8], eax; mov ebx, [rsp-8]', ['RAX'])
    a('mov [rsp-2], ax; mov bx, [rsp-2]', ['RAX'])
    a('mov [rsp-1], al; mov bl, [rsp-1]', ['RAX'])
    a('push rax; xadd qword ptr [rsp], rbx; pop rcx', ['RAX', 'RBX'])
    return c


CORPORA = {'arm64': _arm64, 'mips': _mips, 'ppc': _ppc, 'riscv': _riscv, 'x86_64': _x86}
