"""The appendix's overhead ladder table, from overhead_ladder.json.

The table was written out by hand, so a re-run could move a rung without it
following.  Every value in it is either in the ladder JSON or a ratio of two
values that are.

    python gen_ladder_table.py overhead_ladder.json --tex ladder.tex
    python gen_ladder_table.py overhead_ladder.json --md ladder.md

Columns, and where each comes from:

  ql.run    `run_s`, the measured phase alone: ql.run() for the emulated rungs
            and the whole subprocess for `native`, which has no such phase
  wall      `wall_s`, which adds interpreter start-up and emulator
            construction, both of which a user of the tool also waits for
  CPU       `cpu_s`
  RSS       `peak_rss_mib`
  ns/instr  run_s over the guest instruction count the run recorded
  x native  run_s over the native rung's
  x qiling  run_s over the qiling-only rung's

The two baselines the last two columns divide by are named rather than assumed
to be first and second, and a ladder missing either of them is refused: a
column of ratios against a rung that was not measured is a column of noise.
"""
# Experiment script, not library code: see artifacts/ndss27/README.md,
# "Lint and type checking", for why annotations are not required here.
# mypy: disable-error-code="no-untyped-def, no-untyped-call, type-arg"
from __future__ import annotations

import argparse
import json
import sys

NATIVE = 'native'
QILING = 'qiling-only'

#: The groups the appendix sets the ladder in, and the rungs of each.  The C
#: rungs are a nested chain, so each one's marginal cost is attributable to the
#: single thing it adds.  The Python rungs measure the same granularity in the
#: other host language and are not an increment on the row above.
GROUPS = [
    ('Nested chain', [NATIVE, QILING, 'c-blockhook', 'c-codehook',
                      'c-codehook-regs']),
    ('Same granularity, hosted in Python', ['blockhook', 'codehook',
                                            'codehook-regs']),
    ('microtaint', ['microtaint-plumbing', 'microtaint-none',
                    'microtaint-all']),
]


def rows(lad):
    """(group, rung, cells) for every rung, in the appendix's order.

    A rung the ladder holds and GROUPS does not is kept, under its own
    heading.  Dropping it would make a new rung invisible in exactly the table
    that exists to list them all.
    """
    layers = lad['layers']
    instrs = lad.get('guest_instructions') or 0
    for key in (NATIVE, QILING):
        if key not in layers:
            raise SystemExit(
                f'this ladder has no `{key}` rung, so the columns that divide '
                f'by it cannot be computed.  Re-run overhead_ladder.py.',
            )
    base_native = layers[NATIVE]['run_s']
    base_qiling = layers[QILING]['run_s']

    named = {k for _, ks in GROUPS for k in ks}
    groups = [*GROUPS]
    extra = [k for k in layers if k not in named]
    if extra:
        groups.append(('Not in the appendix', extra))

    out: list[tuple] = []
    for title, keys in groups:
        present = [k for k in keys if k in layers]
        if not present:
            continue
        out.append((title, None, None))
        for k in present:
            d = layers[k]
            run = d['run_s']
            out.append((None, k, {
                'desc': d.get('desc', ''),
                'run_s': run,
                'wall_s': d.get('wall_s'),
                'cpu_s': d.get('cpu_s'),
                'rss': d.get('peak_rss_mib'),
                'ns_per_instr': (run * 1e9 / instrs) if instrs else None,
                'x_native': (run / base_native) if base_native else None,
                'x_qiling': (run / base_qiling) if base_qiling else None,
                'n_runs': d.get('n_runs'),
            }))
    return out


def _num(x, decimals, thin=r'\,'):
    if x is None:
        return '---'
    s = f'{x:,.{decimals}f}'
    whole, _, frac = s.partition('.')
    return whole.replace(',', thin) + ('.' + frac if frac else '')


def as_tex(lad):
    head = [
        '% Generated by gen_ladder_table.py.  Do not edit by hand.',
        r'\begin{table*}[t]', '    ' + r'\centering', '    ' + r'\footnotesize',
        '    ' + r'\caption{Every rung of the overhead ladder. \texttt{ql.run} '
                 r'is the taint phase; \emph{wall} adds interpreter start-up '
                 r'and emulator construction, which a user of the tool also '
                 r'waits for.}',
        '    ' + r'\label{tab:appendix-ladder}',
        '    ' + r'\begin{tabular}{@{}llrrrrrrr@{}}', '        ' + r'\toprule',
        '        ' + r'Rung & What it adds & \texttt{ql.run} (s) & wall (s) & '
                     r'CPU (s) & RSS (MiB) & ns/instr & $\times$native & '
                     r'$\times$qiling \\',
        '        ' + r'\midrule',
    ]
    body = []
    for title, key, c in rows(lad):
        if key is None:
            body.append('        ' + r'\multicolumn{9}{@{}l}{\emph{%s}} \\'
                        % title.replace('microtaint', r'\ourname'))
            continue
        body.append('        ' + ' & '.join([
            r'\texttt{%s}' % key.replace('_', r'\_'),
            c['desc'],
            _num(c['run_s'], 3), _num(c['wall_s'], 3), _num(c['cpu_s'], 3),
            _num(c['rss'], 0), _num(c['ns_per_instr'], 1),
            _num(c['x_native'], 0) + r'$\times$',
            _num(c['x_qiling'], 1) + r'$\times$',
        ]) + r' \\')
    return '\n'.join([*head, *body, '        ' + r'\bottomrule',
                      '    ' + r'\end{tabular}', r'\end{table*}']) + '\n'


def as_md(lad):
    out = ['<!-- Generated by gen_ladder_table.py. Do not edit by hand. -->', '',
           '### Every rung of the overhead ladder', '',
           '`ql.run` is the taint phase. `wall` adds interpreter start-up and',
           'emulator construction, which a user of the tool also waits for.', '',
           ('| Rung | What it adds | ql.run (s) | wall (s) | CPU (s) '
            '| RSS (MiB) | ns/instr | x native | x qiling | runs |'),
           '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    for title, key, c in rows(lad):
        if key is None:
            out.append(f'| **{title}** |' + ' |' * 9)
            continue
        out.append('| ' + ' | '.join([
            f'`{key}`', c['desc'],
            _num(c['run_s'], 3, ''), _num(c['wall_s'], 3, ''),
            _num(c['cpu_s'], 3, ''), _num(c['rss'], 0, ''),
            _num(c['ns_per_instr'], 1, ''), _num(c['x_native'], 0, ''),
            _num(c['x_qiling'], 1, ''), str(c['n_runs'] or '---'),
        ]) + ' |')

    # The provenance belongs with the table: a ladder is only comparable with
    # another one on the same workload, and boost changes every row.
    cpu = lad.get('cpu') or {}
    eng = lad.get('engine') or {}
    workload = (f"Workload: {_num(lad.get('guest_instructions'), 0, '')} guest"
                f" instructions, {lad.get('stdin_bytes')} bytes of input.")
    boost = (f"CPU boost: {cpu.get('cpu_boost')}"
             f" ({cpu.get('detected_via') or 'not recorded'}).")
    out += ['', workload,
            f"Engine: {eng.get('describe') or eng.get('version') or '?'}.",
            boost]
    return '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('ladder', help='an overhead_ladder.json')
    ap.add_argument('--tex', metavar='PATH')
    ap.add_argument('--md', metavar='PATH')
    args = ap.parse_args()

    with open(args.ladder) as fh:
        lad = json.load(fh)
    if not lad.get('guest_instructions'):
        print('[!] this ladder did not record a guest instruction count, so '
              'the ns/instr column is empty', file=sys.stderr)

    if args.tex:
        with open(args.tex, 'w') as fh:
            fh.write(as_tex(lad))
        print(f'[+] wrote {args.tex}')
    if args.md:
        with open(args.md, 'w') as fh:
            fh.write(as_md(lad))
        print(f'[+] wrote {args.md}')
    if not (args.tex or args.md):
        print(as_md(lad))
    return 0


if __name__ == '__main__':
    sys.exit(main())
