"""Taint must survive a round trip through the XMM register file.

`movq xmm0,rax; <simd op>; movq rax,xmm0` moves taint out of a general-purpose
register, through a vector lane, and back. Three sequences from the RQ2 corpus
exercise it, with the values and taints the benchmark actually generated.

Why these three are worth a file of their own: the RQ2 harness reported all
three as under-taints for months, and only one of them was the engine. The
harness named its vector state_format entries `XMM0_LO`/`XMM0_HI`, which the
mapper does not resolve -- the compute path tracks vector registers as
geometry-derived 8-byte lanes called `VL_<sleigh-byte-offset>`. An unresolvable
state_format entry is silently inert: no error, just an instruction whose SIMD
taint has nowhere to live. So the benchmark measured its own naming and called
it an engine bug. Build the state_format through `RegisterAliases`, which
derives the lane names from pypcode's own register geometry, and two of the
three come back bit-exact.

The third is real, and bisecting the tags places it exactly. Ground truth is
0x6080000000800000; each cell is what reaches RAX:

    v0.6.9   0xe0e0e0e0e0e0e000   sound (over-tainted), and what the paper recorded
    v0.6.10  0xe0e0e0e0e0e0e000   sound
    v0.6.11  0xe000               UNSOUND
    v0.6.12  0xe000               UNSOUND
    v0.6.13  0x0                  UNSOUND
    v0.6.14  0x0                  UNSOUND
    v0.6.15  0x0                  UNSOUND

So it broke in v0.6.11, the release that also introduced the geometry lane names,
and got worse in v0.6.13. On HEAD, truncating the sequence shows where the taint
goes: the first four instructions return 0xe0e0e0e0e0e0e000 and inserting
`psllq xmm0,8` before the writeback returns 0. It is marked xfail; when it is
fixed, remove the marker rather than the test.

Soundness is what is asserted -- the engine mask must CONTAIN the ground-truth
mask. Over-taint is a precision cost the engine is allowed to pay.
"""

from __future__ import annotations

import pytest

from microtaint.debug.reg_aliases import RegisterAliases
from microtaint.types import Architecture
from tests.oracle_harness import UC_DESCS, ground_truth, reference_taint

_A = RegisterAliases(Architecture.AMD64)
_REGS = _A.state_format(['RAX', 'RBX', 'RCX', 'RDX', 'RSI', 'RDI', 'XMM0', 'XMM1'])

# Values and taints as generated by benchmark.py at seed 12 (cases 8496, 8352,
# 8002 of the 9,858-case RQ2 corpus).
_STATE = {
    'paddq': ({'RAX': 0x2B15EF852248345B, 'RBX': 0x2F6AC483875C5EBB,
               'RCX': 0x9E18CEAF4CCB78A1, 'RDX': 0x78FC36BB52AFBFFE},
              {'RBX': 0x100000, 'RCX': 0x20000}),
    'pand': ({'RAX': 0x2E3D676D24C55DF1, 'RBX': 0x3D8EEBADB5A0557E,
              'RCX': 0x0CD2A81B0AFCE899, 'RDX': 0x435861CFFFDB4206},
             {'RAX': 0x200000040200, 'RBX': 0x800000,
              'RCX': 0x200000008, 'RDX': 0x800000000080000}),
    'psllq': ({'RAX': 0x2E3D676D24C55DF1, 'RBX': 0x3D8EEBADB5A0557E,
               'RCX': 0x0CD2A81B0AFCE899, 'RDX': 0x435861CFFFDB4206},
              {'RAX': 0x20800000000000, 'RBX': 0x4000, 'RCX': 0x400000000}),
}

_MOVQ_XMM0_RAX = '66480f6ec0'
_MOVQ_XMM1_RBX = '66480f6ecb'
_MOVQ_RAX_XMM0 = '66480f7ec0'
_MOVQ_IN = _MOVQ_XMM0_RAX + _MOVQ_XMM1_RBX
_MOVQ_OUT = _MOVQ_RAX_XMM0

_SEQUENCES = {
    # A packed 64-bit add is one lane wide, so bit i of either operand reaches
    # output bit j for every j >= i through the carry.  This is the case whose
    # ground truth is checkable by hand: 0x2b15…345b + 0x2f6a…5ebb ends …a9a49316,
    # and clearing RBX bit 20 gives …a9949316, so bits 20 AND 21 move.
    'paddq': _MOVQ_IN + '660fd4c1' + _MOVQ_OUT,
    'pand': _MOVQ_IN + '660fdbc1' + _MOVQ_OUT,
    # paddb xmm0,xmm1 ; pxor xmm0,xmm1 ; psllq xmm0,8
    'psllq': _MOVQ_IN + '660ffcc1' + '660fefc1' + '660f73f008' + _MOVQ_OUT,
}


def _under(code_hex: str, key: str) -> dict[str, int]:
    """Ground-truth bits the engine leaves clean, per register."""
    values, taint = _STATE[key]
    code = bytes.fromhex(code_hex)
    desc = UC_DESCS['AMD64']()
    truth = ground_truth(desc, code, taint, values)
    got = reference_taint(Architecture.AMD64, code, _REGS, taint, values)
    return {r: t & ~got.get(r, 0) for r, t in truth.items() if t & ~got.get(r, 0)}


def test_lane_names_come_from_the_alias_table() -> None:
    """XMM0 is two 64-bit lanes and neither is called XMM0_LO."""
    names = {r.name for r in _REGS}
    lanes = _A.to_engine_names('XMM0')
    assert len(lanes) == 2
    assert set(lanes) <= names
    assert 'XMM0_LO' not in names


def test_paddq_carries_through_the_lane() -> None:
    assert _under(_SEQUENCES['paddq'], 'paddq') == {}


def test_pand_carries_through_the_lane() -> None:
    assert _under(_SEQUENCES['pand'], 'pand') == {}


@pytest.mark.xfail(strict=True, reason='psllq xmm,imm8 clears the lane taint instead of shifting it')
def test_psllq_carries_through_the_lane() -> None:
    assert _under(_SEQUENCES['psllq'], 'psllq') == {}
