"""Emit every Table 6 number as a LaTeX macro, so prose and measurement agree.

    python gen_avalanche_macros.py base64.json nftables.json siphash.json \
        --out ../../../paper/avalanche_numbers.tex

Table 6 and the three observations around it were hand-written percentages.  The
category profile, the exactly-handled range, the data and flag shares and the
sample sizes all move whenever the engine's taxonomy or approximation set moves,
and a hand-written number cannot move with them.  That is how "84--100%" and
"no over-approximation" survived a rewrite of the multiply and shift terms.
"""
from __future__ import annotations

import argparse
import json
import os

#: Categories the paper calls exactly handled.
EXACT_CATS = ('Mapped', 'Transportable', 'Translatable', 'Monotonic')
#: Order of the rows in Table 6.
ROW_CATS = ('Mapped', 'Transportable', 'Translatable', 'Monotonic',
            'Transportable (Eq)', 'Weldable', 'Avalanche')
#: LaTeX-safe short name per workload.
#
#: A TeX control sequence is letters only, so these tags must contain no digit,
#: hyphen or space.  `base64-debian12` maps to the same `Bsf` the paper already
#: uses, because that workload IS the reference column: Debian 12's own
#: coreutils binary, extracted from a hash-pinned .deb, identical on every
#: machine.  The other two base64 builds get their own tags so they can be
#: quoted as variants without colliding with it.
TAG = {'base64': 'Bsf',
       'base64-debian12': 'Bsf',
       'base64-static': 'BsfStatic',
       'base64-system': 'BsfSystem',
       'nftables': 'Nft', 'siphash': 'Sip'}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('reports', nargs='+', help='avalanche_freq.py --json-out files')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    data = {}
    for f in args.reports:
        with open(f) as fh:
            d = json.load(fh)
        if d.get('failures'):
            raise SystemExit(
                f'{f}: the run recorded {sum(d["failures"].values())} silent-path '
                f'failure(s), so its table is computed over a reduced population. '
                f'Fix the run before generating macros from it.')
        data[d['title']] = d

    v: dict[str, str] = {}
    exact_shares = []
    flag_shares = []
    for title, d in data.items():
        # Refuse an unknown workload rather than inventing a tag from its title.
        # `title.title()` turned `base64-debian12` into `Base64-Debian12`, and a
        # macro named \avlBase64-Debian12N is not a control sequence at all: the
        # file would have been written and only broken later, inside LaTeX.
        if title not in TAG:
            raise SystemExit(
                f'unknown workload title {title!r}: add it to TAG with a '
                f'letters-only tag before generating macros from it.')
        t = TAG[title]
        ic, st = d['insn_count'], d['stats']
        n = sum(ic.values())
        v[f'avl{t}N'] = f'{n:,}'.replace(',', '{,}')
        for c in ROW_CATS:
            key = f'avl{t}{c.replace(" ", "").replace("(", "").replace(")", "")}'
            v[key] = f'{100 * ic.get(c, 0) / n:.1f}' if ic.get(c) else '---'
        do, da = st['data_out_bits'], st['data_aval_bits']
        fo, fa = st['flag_out_bits'], st['flag_aval_bits']
        v[f'avl{t}Data'] = f'{100 * da / do:.1f}' if do else '0.0'
        v[f'avl{t}Flag'] = f'{100 * fa / fo:.1f}' if fo else '0.0'
        # The headline: does the conservative fallback decide any DATA bit?
        v[f'avl{t}AvalData'] = f"{d.get('asg_data_aval', {}).get('Avalanche', 0)}"
        exact_shares.append(100 * sum(ic.get(c, 0) for c in EXACT_CATS) / n)
        if fo:
            flag_shares.append(100 * fa / fo)

    v['avlExactLo'] = f'{min(exact_shares):.0f}'
    v['avlExactHi'] = f'{max(exact_shares):.0f}'
    v['avlFlagLo'] = f'{min(flag_shares):.0f}'
    v['avlFlagHi'] = f'{max(flag_shares):.0f}'
    # True iff the Avalanche category decides no data bit anywhere: the claim the
    # prose makes, so it must be derived rather than asserted.
    total_av_data = sum(int(v[f'avl{TAG[t]}AvalData']) for t in data if t in TAG)
    v['avlAvalDataTotal'] = f'{total_av_data}'

    lines = ['% Auto-generated by gen_avalanche_macros.py from '
             + ', '.join(os.path.basename(f) for f in args.reports)
             + '. Do not edit by hand; re-run the script.']
    for k in sorted(v):
        lines.append(f'\\newcommand{{\\{k}}}{{{v[k]}}}')
    with open(args.out, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    print('\n'.join(lines))
    print(f'\n% wrote {args.out}')
    if total_av_data:
        print(f'% NOTE: the Avalanche category decides {total_av_data} data bit(s); '
              'the prose claim that it decides none is no longer true.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
